== Chapter 1. The Death of the Immortal Soul

In the beginning God created all things good.
Being inherently and immutably good Himself,
every creation of His must necessarily be so,
according to their several kinds in which He created them.
As man was entirely made by Him, so he must have been made entirely good.
His nature was clear of all impurity, and free from all defect and disorder.
His faculties were perfect, though limited to their proper sphere,
and every part of his composition was constituted in its due rectitude.
The body was placed in subservience to his rational spirit or soul
(which is the more noble and excellent part, created for immortality);
and this was placed in subjection to the guidance of its Creator.

The human faculties were originally clear, unprejudiced, and fit to receive impressions.
Since man could not have brought any real knowledge into the world with him,
all knowledge must either have been immediately communicated to him by his Maker,
or afterwards acquired by himself through observation and experience.
The latter took time to acquire,
but he no doubt found himself immediately endowed with a sufficient understanding
of himself and his Creator as related to both his present duty and happiness.

Not only was man supplied with a measure of light and understanding,
but he was doubtless empowered to act according to it,
otherwise his knowledge would have been given to him in vain.
Yet, though he most certainly was enabled to obey,
what followed demonstrated that he was placed by God into a state of probation,
else he would not have been held guilty for his failure;
for his Maker could surely have fixed him in a state of immutable virtue and goodness,
had He so desired.

The omniscient Creator no doubt foresaw what a
subtle adversary man would have to encounter,
and so furnished him with means sufficient to
discover his snares and resist his assaults.
If Satan was allowed to use his subtlety and influence to deceive him,
surely man was not only warned,
but also endowed with sufficient divine light and power to withstand his attempts,
as he kept watchful unto his Maker (for nothing short of the
divine nature can enable any intelligent creature to resist
temptation and act according to the divine will.)

God created man for the purpose of His own glory; and in order to glorify Him,
and to partake of His glory, man must walk in conformity to His will.
But man can neither rightly know His will, nor constantly perform it,
merely by the strength of his own faculties.
Therefore, the first man must necessarily have been assisted by the Spirit of God,
and enabled to perform His will in such a way as to
glorify his Creator and answer the end for his creation.
Hence it is concluded that Adam was first created a natural man,
and then rendered a spiritual one by
the quickening power of the Spirit of Christ--for
"`the spiritual is not first, but the natural, and afterward the spiritual.`"^
footnote:[1 Corinthians 15:45]
This spiritual life is the true life,
and the proper element in which immortal souls are to live and move.

Thus the parents of mankind, in their original and uncorrupted state,
were fit temples for the Holy Spirit to dwell in.
They were "`partakers of the divine nature,`"^
footnote:[2 Peter 1:4]
recipients of the breath of the power of God,
the pure influence flowing from the glory of the Almighty.
It was undoubtedly in the light of this pure influence that Adam had
such an intuitive discerning of the creation as enabled him to give
names to all creatures according to their several natures.
For we read, "`the Lord God formed every beast of the field and every bird of the air,
and brought them to Adam to see what he would call them.
And whatever Adam called each living creature, that was its name.`"^
footnote:[Genesis 2:19]

Under this heavenly endowment,
the holy impression of the divine image clearly appeared in
the first of mankind--"`In the image of God created He them.`"^
footnote:[Genesis 1:27]

Now, had man kept in faithful obedience to his heavenly Guide,
and rejected the efforts of the tempter, he might undoubtedly, in due time,
have grown to a degree of establishment beyond all possibility of falling.
But not continuing in a state of watchfulness,
and (contrary to the warning which was given him)
turning his attention towards the temptation,
he dropped his guard, and let go that Spirit wherein his life and strength lay.
Indeed, he fell from it and from all its advantages,
out of the liberty of the sons of God,
into the bondage of corruption--a sure introduction into misery.
(For as holiness and happiness are inseparably united,
so sin and misery are indivisibly connected.)

To suppose that the almighty Author of all good created man with a
moral _necessity_ to transgress upon the appearance of temptation,
is an imagination too injurious to the divine character to be admitted.
Our first parents were unquestionably enabled by their Maker to abide in watchfulness,
which would have allowed them to experience preservation.
Their defection from this was certainly not of Him, but of themselves.
Had their failure been through the Lord`'s will,
or by the intentional design of their circumstances so
that sin must inevitably have followed,
He could not consistently have punished them for it as being contrary to His will.

A dangerous fondness for becoming knowledgeable in hurtful and unnecessary
things seems to have had an early entrance into the human mind.
"`In the day you eat, your eyes shall be opened, and you shall be as gods,
knowing good and evil.`"^
footnote:[Genesis 3:5]
By the suggestion of this flattering falsehood, Eve was deceived.
Knowing nothing but good, she might have remained happy; but experiencing evil,
she became otherwise.

This sort of knowledge is as opposite to that of divine wisdom as darkness is to light.
It is certain the omniscient God knows both good and evil,
but He knows the first by unchangeable possession and perfect enjoyment,
and the last He beholds with abhorrence, in eternal opposition to,
and infinite distance from, the purity of His nature.
Yet with sinful man the case is the reverse: evil has immediate possession of him,
and good is out of his reach.
Without divine mercy, he must remain completely wretched.
This is the necessary consequence of that boasted knowledge of the world
which men acquire by tasting the deadly and poisonous sweets of temptation.

The consequences of this failure immediately affected the actual transgressors,
and remotely influenced all their posterity.
Adam and Eve lost the bright impression of the divine image,
and all the joys attending it.
Having forfeited the immediate indwelling and pure influence of God`'s Holy Spirit,
they lost that divine likeness wherein they had enjoyed internal light, life, love,
goodness, righteousness, holiness, and happiness.
That all-present Spirit of power, truth, and virtue,
which in their original state had been their covering and comforter,
now disunited from them through transgression, and became their accuser and convictor.

Having departed from under a due and constant
subjection to the mind and Spirit of his Creator,
the will of man separated from the will of God, and became _self-will._
And by his unfaithful self-gratification, and letting in the suggestion of the tempter,
man`'s chief love turned from his Maker to himself.
In this way, inordinate self-love and self-will originated in man,
which always stand in a will separate from the will of God,
and a spirit contrary to His Holy Spirit.
Moreover, this separation opened an easy road of access for the evil
spirit to influence the human mind towards exterior objects,
and rendered them the perpetual subjects of temptation.
Giving way to carnal inclinations, man became carnally-minded;
and "`to be carnally minded is death.`"^
footnote:[Romans 8:6]

When the Sovereign Legislator first gave a positive command to Adam,
He pronounced immediate death upon him in the case of transgression;
"`In the day that you eat of it, you shall surely die.`"^
footnote:[Genesis 2:17]
This seems to imply a much deeper and more important
meaning than what relates to the natural body;
a meaning more immediately affecting the rational soul, namely:
the privation of a life which before transgression it happily enjoyed, and which,
by disobedience, it must certainly lose.

What then is the proper life of the soul?
And what is the death of a soul, seeing it does forever exist?
Merely _to exist_ cannot be the life intended.
The true life of a soul must be to live in that
life which exists only in the divine nature,
and which is not to be enjoyed except by partaking of the divine nature;
i.e. to live in the Spirit of Him who is the life which
the Evangelist declares to be the true light of men.
This supernatural, spiritual,
heavenly power and virtue of the great Illuminator and Quickener,
is the true life of the immortal spirit of man;
and the total lack or deprivation thereof, is its death.

Turning from this life to embrace temptation, our first parents did surely deviate from,
and die in spirit to, that divine life by which they had been quickened.
For, "`It is the Spirit that gives life;`"^
footnote:[John 6:63]
and when life departs, death ensues naturally.
As the body dies when deprived of its natural life,
so the soul is left in a state of spiritual death when
that which is its proper life departs from it;
save this difference--that the deceased body remains wholly insensible, but the soul,
in its state of death, still exists under the unavoidable sense of its guilt and misery.
