== Chapter 2. The Creature Subjected to Vanity

It appears from holy Writ, that previous to our own actual offenses,
we are all naturally affected by the transgression of our first parents.
"`By one man sin entered into the world, and death by sin, so death passed upon all men,
for all have sinned.`"^
footnote:[Romans 5:12]
This is not to be understood of the death of the body only;
for indeed all come into the world in the image of the earthly man,
and void of the quickening and sensible influence of divine life.

This being true,
there appears no necessity to conclude that we all come into
the world justly obnoxious to divine vengeance for an offense
committed by our primogenitors before we came into the world.
With what propriety can an infant, incapable of committing any crime,
be treated as an offender?
Scripture positively assures us, "`God`'s ways are equal,`"^
footnote:[Ezequiel 18:25, 29]
and "`The soul that sins, it shall die,`"
and "`Not the son for the fault of the father,`"^
footnote:[Ezequiel 18:20] etc.
Whatever Adam`'s posterity lost through him, that and more they gain in Christ;
and undoubtedly His mercy and goodness, and the extent of His propitiation,
are as applicable to infants, who have not personally offended, as to adults who have.

The immortal, reasonable soul of man, in every individual,
appears to be the immediate production of its Creator; for the prophet Zechariah,
speaking of the great acts of God in creation, asserts,
that "`He forms the spirit of man within him.`"^
footnote:[Zechariah 12:1]
And in Ecc. 12:7, we read that upon the death of the body,
"`Then shall the dust return to the earth as it was,
and the spirit shall return unto God who gave it.`"
Therefore, the soul itself,^
footnote:[i.e. as a created vessel for a nature.]
receiving its existence immediately from the perfection of unchangeable purity,
can have no original impurity or corruption in it.
However, being immediately and intimately connected with a natural body,
and unable to withstand the passions of a carnal nature,
the soul is liable to be so influenced by them as to
partake with them in their sensual indulgences.
In this state the descendants of Adam come into the world,
destitute of that divine life from which Adam fell.

Whatever were the peculiarities attending the fall of the first man and woman,
this is certain--that their progeny do not come into the world in
that same state of brightness in which they were first created.
It cannot escape the notice of those who have had the care of infants,
that the earliest exertions observable in them evidently arise
from the powers of carnal desire and passion,
and that these are prone to increase in them, and to predominate as they grow up.
Indeed, what effort and attention are required to keep children out of
unruliness and intemperance as they advance to a youth`'s state!
How eagerly they permit inordinate desire to govern their rational faculties!
And what pains are necessary (through a careful and virtuous
education) merely to regulate or mitigate these natural tendencies.
Doubtless they could never be truly subdued and ruled
without the operation of a superior principle.

Previous to the reception of any knowledge,
the soul is joined to the body by the power of its Creator, who saw fit it should be so.
"`For,`" says the apostle, "`the creature was made subject to vanity, not willingly,
but by reason of Him who has subjected it in hope;
because the creature itself also shall be delivered from the bondage of corruption,
into the glorious liberty of the children of God.`"^
footnote:[Romans 8:20-21]
The rational soul is here intended by the term "`creature,`"
and properly designates the man.
Herein lies the true distinction between the
human species and creatures of inferior kinds.

This soul is not handed down with the body from parents to children,
being an indivisible, immaterial substance which cannot be generated by man.
The soul of the child was never in the parent, and therefore could never sin in him,
nor derive guilt from his transgression.
Neither can guilt accrue to it merely from its being
joined to a physical body descended from him,
for this junction is the act of the Creator.
To account a child guilty, or worthy of punishment,
merely for an offense committed by its parents,
before it could have any consciousness of being,
is inconsistent with both justice and mercy.
Therefore, though lacking spiritual life, no infant is born with guilt upon its head.^
footnote:[Note by Joseph Phipps--Respecting little children
who are taken away before they have personally offended,
they cannot in equity be chargeable,
but may with just confidence be resigned as perfectly
safe in the arms of their Savior who declared,
"`Of such is the kingdom of heaven.`"]

Nevertheless, in addition to our natural alienation from, and ignorance of,
the internal life of God in our fallen state,
it must be acknowledged that all who have arrived to such a degree of
maturity as to be capable of receiving a right understanding,
and of distinguishing the inward admonitions of Truth in their conscience,
have also increased and strengthened the bonds of corruption upon themselves,
in different degrees, by a repeated, and often habitual indulgence of the carnal part,
contrary to the sense of duty received.
These have more deeply entered into the dark region of the
shadow of death through their own trespasses and sins.
Thus, "`All have sinned, and come short of the glory of God.`"^
footnote:[Romans 3:23]
