== Chapter 3. The Offer of Perfect Redemption

Whatever we may have derived from our parents,
we certainly accumulate to ourselves additional corruption.
"`All flesh has corrupted their way upon the earth.`"^
footnote:[Genesis 6:12]
Every adult person, in his common natural state, must, upon serious reflection,
find in himself a proneness to the gratification of self,
an eager inclination at times to forbidden pleasure,
an aversion to piety and holy living, a consciousness of guilt,
and a fearful apprehension of the approach of death.
Men generally confess they have erred and strayed, like lost sheep,
from the wholesome paths of virtue and duty;
and that their frailty is such that it is an easy thing to fall in with temptation,
but a hard (if not impossible) thing to effectually resist it.
Indeed, even the high rewards promised to virtue and a good life,
and the sore punishments connected to vice and folly,
are altogether insufficient to retain men in the practice of the former,
or to enable them to conquer the force of their inclination to the latter.

This clearly demonstrates the corruption of their nature.
Christ said, "`Out of the abundance of the heart the mouth speaks;`"^
footnote:[Luke 6:45]
and so man finds that his outward practice arises from whatever lodges and governs within.
The corruption in the heart affects all actions, manners, and language.
From here springs all immorality in conduct, all profane and untrue speeches,
and all desperate attempts to gratify the pride and folly of vain minds.
As the origin of evil in man resulted from turning his attention and desire from
the Creator to the creature
(thus dividing his will from the will of God, and his spirit from the Spirit of God),
so the continuation of evil in man is by the continuance of this separation,
and it must abide so long as that separation remains.
In this situation, commonly called the _state of nature,_ we are both unfit for,
and unable to enter the heavenly kingdom, which admits nothing sinful or unclean.

It is therefore absolutely necessary that man should be made holy, in order to be happy.
Holiness cannot unite with unholiness; nor can ability arise from perfect weakness.
If pollution could cleanse itself, if evil could produce good,
if death could bring forth life, then man, thus corrupted, debilitated, and deadened,
might be able to reform, quicken, and restore himself.
But it is not in the power of man to extricate himself from the bonds of sin and death.
Therefore, as sin separates man from his Maker, man must be separated from sin,
or he cannot be reconciled and united to Him.
Without restoration to a state of holiness,
he can never enjoy the felicity belonging to that state; for,
"`without holiness no man shall see the Lord.`"^
footnote:[Hebrews 12:14]

How then shall corrupt man become holy?
How shall he, in a state of utter incapacity,
enter into warfare against his many and mighty
adversaries which beset him within and without?
What ability has he to fight an enemy who has already enchained him?
Indeed, a power too strong for man has got possession;
and so it must be a superior power that liberates, rescues, and restores him.
Who is sufficient for these things?
None but man`'s omnipotent Creator is able to unbind and extricate him.
But alas, Adam departed from His will, transgressed His law, disobeyed His command,
and committed a great offense.

Yet, behold the astonishing compassion and kindness of infinite Goodness!
An all-sufficient means was provided for the redemption
both of the actual offenders and all their progeny.
The eternal Word, the Son, the Lamb of God Almighty,
demonstrated the greatness of divine love and mercy,
_first_ by concurring with the Father to yield Himself up
in due time to take the nature of man upon Him,
and, by resigning it to suffering and death,
to make it a propitiation for the whole species;
and _second,_ by immediately, and all along,
affording "`a manifestation of His Holy Spirit to every man to profit withal,`"^
footnote:[1 Corinthians 12:7]
in order to affect their present deliverance from the power of sin,
and their everlasting salvation from the certain effect of abiding in sin, namely,
the second death.

That man should, of himself,
empower himself to live in the constant practice of
crossing his natural inclinations and propensities,
is a wild presumption; but that an infinitely good Spirit,
being more powerful than all of man`'s enemies, should so influence, incline,
and enable him, is highly reasonable to believe, because it is absolutely necessary.
The possibility of man`'s purification and sanctification by
the Holy Spirit cannot reasonably be doubted,
since the omnipotent One is certainly more able to cleanse, than the creaturely, corrupt,
and fallen powers of darkness are able to defile.
If the sovereign Lord did not intend that man should be made holy,
He would not require it;
nor would He require it without affording him the assistance necessary to accomplish it,
for He demands no impossibilities.

Now, that He _does_ require it, the sacred writings sufficiently bear witness.
"`God,`" says an apostolic writer,
"`has not called us to uncleanness, but unto holiness.`"^
footnote:[1 Thessalonians 4:7]
And, "`Christ also loved the church, and gave Himself for it,
that He might sanctify and cleanse it with the washing of water by the word,`"
or the purifying efficacy of the Holy Word,
or Spirit, which cleanses the soul as water does the body,
"`so that He might present it to Himself a glorious church, not having spot or wrinkle,
or any such thing; but that it should be holy and without blemish.`"^
footnote:[Ephesians 5:25-27]
Elsewhere, he writes, "`Therefore, having these promises, beloved,
let us cleanse ourselves from all filthiness of the flesh and spirit,
perfecting holiness in the fear of God.`"^
footnote:[2 Corinthians 7:1]
In still another place, he gives this exhortation:
"`Abstain from all appearance of evil,`"--then proceeds--
"`And may the God of peace Himself sanctify you completely;
and may your whole spirit, and soul, and body,
be preserved blameless unto the coming of our Lord Jesus Christ.`"
And to encourage them to seek it and hope for it, he immediately assures them,
"`Faithful is He that calls you, who also will do it.`"^
footnote:[1 Thessalonians 5:22-24]

Vain is the imaginary pretense that Christ has paid the whole price for us,
by which we may stand fully acquitted in the
sight of God and have complete redemption in Him,
_without_ sanctification in ourselves.
For, were this the real truth,
then Christ paid the price of redemption so that
man might continue in a state of pollution,
and practice evil with security, or be justified in breaking the known commands of God,
serving Satan during his whole term of life.
Contrary to this, the apostolic doctrine is,
"`He Himself bore our sins in His own body on the tree, that we, being dead to sin,
should live unto righteousness.`"^
footnote:[1 Peter 2:24]
And "`He died for all, that they who live should no longer live unto themselves,
but unto Him who died for them.`"^
footnote:[2 Corinthians 5:15]
And "`How shall we that are dead to sin live any longer therein.`"^
footnote:[Romans 6:2]
And "`Let not sin therefore reign in your mortal body,
that you should obey it in its lusts.`"^
footnote:[Romans 6:12]
For "`What fruit had you then in those things whereof you are now ashamed?
For the end of those things is death.
But now being made free from sin, and become servants to God,
you have your fruit unto holiness, and the end, everlasting life.`"^
footnote:[Romans 6:22-23]

It is true, the apostle says,
"`By one offering He has perfected forever those who are being sanctified.`"^
footnote:[Hebrews 10:14]
But this does not imply that His sacrifice
perfected those who never come to be sanctified.
Here it can mean no more than that those who have so
experienced the effectual operation of divine grace,
as to become sanctified,
have remission by that one offering for the sins
which were committed before their sanctification,
thus perfecting their redemption.
For sin once committed cannot be undone.
Our Savior, therefore, by His sacrifice, manifested the mercy, love, and kindness of God,
being, "`set forth as a propitiation through faith in His blood,
to declare His righteousness, for the remission of sins that are past,
through the forbearance of God.`"^
footnote:[Romans 3:25]
Herein it is shown, that a door of reconciliation is opened to all men; but those who,
through unbelief and disobedience to divine grace,
never experience the work of sanctification,
deprive themselves of this unspeakable advantage;
for it is through sanctification that any come effectually to
enjoy the benefit of the sacrifice of Christ.

That outward offering of Christ for "`all men,`"^
footnote:[Romans 5:18-6:10; 1 Tim. 4:10]
manifested the love of God towards all,
and shows that He stands ready to pardon past transgression in all
who sincerely accept His terms of true repentance and reformation.
But our soul`'s salvation is not completed by that single act only,
nor is the work of redemption finished for us without us.
Though Christ died for us, that we might be brought unto glory,
yet we are not actually purified, fitted for,
and introduced into the kingdom by the one outward offering.
The way to reconciliation was indeed opened by the death of Christ;
but we are not saved by His life till we livingly
experience the work of salvation in our own particulars.
Indeed we must "`receive with meekness the implanted Word,
which is able to save our souls,`"^
footnote:[James 1:21]
and learn to "`work out our own salvation with fear and trembling;
for it is God who works in you both to will and to do for His good pleasure.`"^
footnote:[Philippians 2:12]
"`For if when we were enemies we were reconciled to God through the death of His Son,
much more, having been reconciled, we shall be saved by His life.`"^
footnote:[Romans 5:10]

Perfect redemption then consists, _first,_ in paying the price of ransom;
and _second,_ in bringing out of bondage, and setting the prisoner at liberty.
Our Savior paid the first by His suffering and sacrifice,
and He performs the last by the effectual operation of His Spirit in
the hearts of those who receive Him and resign wholly to Him.^
footnote:[Editor`'s Note:
That this is the doctrine of the apostle appears in his letter to the Ephesians,
where they are first told, "`In Him we have redemption through His blood,
the forgiveness of sin;`" (Eph. 1:7) and then, but a few verses later,
they are commended to the "`Holy Spirit of promise,
who is the earnest of our inheritance until the redemption of the purchased possession.`"
(Eph. 1:14)]

None have cause to murmur at, or complain against,
the dispensations of their benevolent Creator;
for in Christ He has rendered to every child of Adam a full
equivalent for the loss sustained through his unhappy fall.
"`God so loved the world, that He gave His only begotten Son,
that _whosoever_ believes in Him should not perish, but have everlasting life.`"^
footnote:[John 3:16]

God so loved the whole of His rational creation,
that He gave all an opportunity of being saved through believing.
If any do not so embrace it, their refusal is the cause of their condemnation,
and not the lack of God`'s love,
nor the opportunity to accept and receive the benefit of it.
This the four following verses plainly declare:

[quote.scripture]
____
For God sent not His Son into the world to condemn the world,
but that the world through Him might be saved.
He that believes on Him is not condemned; but he that believes not is condemned already,
because he has not believed in the name of the only begotten Son of God.
And this is the condemnation, that light is come into the world,
and men loved darkness rather than light, because their deeds were evil.
For everyone that does evil, hates the light, neither comes to the light,
lest his deeds should be reproved.^
footnote:[John 3:17-20]
____

It is not reasonable to conclude that the whole
world can mean less than the whole human species.
The apostle Peter says,

[quote.scripture]
____
For prophecy never came by the will of man,
but holy men of God spoke as they were moved by the Holy Spirit.
But there were false prophets also among the people,
even as there shall be false teachers among you,
who secretly shall bring in damnable heresies,
[.underline]#even denying the Lord that bought them,#
and bring upon themselves swift destruction.^
footnote:[2 Peter 1:21--2:1, emphasis mine]
____

This Scripture indicates that Christ died not only for those who come to be saved,
but also for those who bring destruction upon themselves;
otherwise it could not be said that, by His sacrifice,
He "`bought,`" or paid the price of redemption, conditionally for them as well as others.
But that He bought even those who deny Him,
and who thereby occasion their own destruction,
is also clearly asserted in the following Scriptures:
"`He, by the grace of God, should taste death for every man;`"^
footnote:[Hebrews 2:9]
and that "`He is the propitiation for our sins, and not for ours only,
but also for the sins of the whole world.`"^
footnote:[1 John 2:2]

It is always necessary that the means be adequate to the end.
Therefore,
since all men in all nations and in every generation
stand in equal relation to their Creator,
and are naturally in absolute need of His help
in order to know purification and salvation,
so the means afforded for this purpose must be universal and able to reach all.
There must be a gift of real and powerful holiness and goodness that
is able to change the condition of man from evil to good.
It must be omnipotent, to enable him to overcome his adversaries--the world, the flesh,
and the devil.
Nothing but a Spirit superior to all these can effectually cleanse the soul,
and operate to the expulsion and exclusion of those subtle and powerful
enemies which continually seek to hold men in the bondage of corruption.
Therefore, nothing but God`'s holy, universal,
almighty Spirit can effect this necessary alteration in man,
rectify the disorder sin has introduced into his nature,
and raise him up from a state of spiritual death,
by producing a new and heavenly birth of divine life in him.
By the work of this Spirit alone,
man can be "`created anew in Christ Jesus unto good works,`"^
footnote:[Ephesians 2:10]
and restored to the image of God in righteousness and true holiness.^
footnote:[Ephesians 4:24]
