== Chapter 4. The Appearance of Christ in the Heart

All exterior forms and ceremonies,
however mistakenly exalted or celebrated amongst mankind,
are but outward and visible signs,
and altogether ineffectual towards any real change or reformation of the person.
The vital part of man`'s religion and duty stands, principally, in a right attention to,
and a faithful obedience of,
the manifestation of the Spirit of Christ in the heart and conscience.
He who pays due and constant regard to this, is in his measure a follower of Christ,
and has, in some degree,
the reality of Christianity in him--irregardless of his system
of religious profession or his location in the world.
For who is a servant of Christ but he that willingly obeys Him?
And if he who acts according to Christ`'s verbal commands is a follower,
is he not also a follower who lacks the knowledge of these written precepts,
but who willingly follows the leadings of His Spirit?

Of this Spirit the truly virtuous and religious amongst the Gentiles were,
in some degree, partakers; "`For,`" says holy Writ,
"`when the Gentiles who have not the law, do by nature the things contained in the law,
these, having not the law, are a law unto themselves;
who show the work of the law written in their hearts;
their conscience also bearing witness,
and their thoughts the meanwhile accusing or else excusing them.`"^
footnote:[Romans 2:14-15]
The words '`by nature`' here, I apprehend,
are not to be understood as if the apostle intended the Gentiles
became virtuous by any goodness in their _fallen_ nature,
which must be the same as all other men`'s.
The context shows he was here distinguishing between
those who enjoyed the ministration of the Mosaic law,
and those who did not.
He uses the expression '`by nature`' in the same sense as if he had said,
'`without an education under the law,`' and proceeds to show that,
though they had it not, yet they practiced the substance intended by the law.
This in no way implies that their hearts _were_ their law,
but rather (as the apostle explains it) that the
work of the law was _written_ in their hearts.
Though they were without the law of Moses, they were not without law to God.
For, by receiving, retaining,
and submitting to the divine impressions in their consciences,
they were under the law of Christ,
or subject to the manifestation of His Spirit in their hearts;
and in proportion to their obedience,
they were partakers of the nature of the Holy Spirit within them.

It is by the internal operation of _this_ nature that they became reformed in
heart and rectified in life and practice (to whatever degree they were);
or as the text has it, were enabled "`to do the things contained in the law.`"
Originally disordered and depraved,
their own nature as men could never have led and empowered them to this;
for it is prone to evil,
and true reformation and religion do not arise from that corrupt ground.
Indeed, all that is good, pure, righteous,
and true comes not by anything in man`'s nature, but by grace.
These are the fruits of that good Seed universally sown
in every heart by the great and good Sower,
who casts seed onto all types of ground for that purpose.
Were it not for the light and power communicated by this internal Holy Spirit,
man could only have proceeded in the increase of corruption, godlessness,
and misery--as appears too evidently by the conduct of those who disregard it.
It is therefore not by following their _own_ nature,
but by obedience to the inward law of the divine nature written in the heart,
that the conscientiously virtuous amongst the Gentiles were enabled to
perform the things (i.e. the just morals) contained in the Mosaic law.
In this way they did evidence, in their measures,
the effectual operation and authority of the divine Lawgiver within them.

The Gentiles, therefore, partaking of the law written in the heart,
cannot properly be said to have been excluded from all share in the gospel.
For the gospel, taken in its full extent, is the revelation of the love and mercy,
and the offer and operation of the grace of God through Christ
to fallen man in his natural and corruptible state,
in order to bring about his restoration and salvation.
It is not limited to the mere tidings; but, in addition to the words goes much deeper,
and essentially consists of the thing declared by them, namely,
_the power of God administered for the salvation of the soul._
By receiving and yielding to this,
the outward coming of Christ is rendered truly and fully effectual to each individual.
Those who believe in and obey Him in His inward and spiritual manifestations
(by which the gospel "`is preached in every creature under heaven`"^
footnote:[Colossians 1:23, Literal Translation]),
may come to be partakers of His life,
and be saved by Him from the second death of eternal misery,
even if they be providentially incapacitated to
know the external history of His incarnation,
death, resurrection, etc.

That virtuous and devout Gentiles were approved of God, appears in the case of Cornelius;
for we find that even before his reception of historical and verbal Christianity,
his sincere devotion and reverence towards his Creator, and charitable acts to the needy,
"`came up for a memorial before God.`"^
footnote:[Acts 10:4]
Moreover,
the Lord now taught Peter (verse 15) that the Gentiles He had thus cleansed
were no more to be esteemed common or unclean than the believing Jews,
and gave clearly to perceive, "`that God is no respecter of persons; but in every nation,
he that fears Him and works righteousness, is accepted with Him.`"^
footnote:[Acts 10:34-35]
Hence it appears,
that those who conscientiously obey the spiritual manifestations of Christ in them,
are internally
(though not necessarily by outward profession)
His disciples and followers,
and truly believe in Him so far as He is revealed to them;
for obedience is the certain proof of a right faith.

I have no doubt that those in any part of the globe, who,
because of inescapable obstacles,
have not the opportunity to hear of historical Christianity,
in their obedience to the spiritual appearance of Christ in their hearts, are accepted,
and partake of the benefits of Christ`'s death.
Why should they not be as capable of receiving the advantage of the sacrifice of Christ,
as they are the disadvantage of the fall of Adam,
when they are equally strangers to the history of both?
But certainly,
those to whom the sacred writings are providentially
communicated are under double obligation,
since they are favored with the additional advantage of the
historical account and written revelation of God to man.
And surely it will tend to their greater condemnation if these believe not unto obedience.
For, irregardless of how strongly and strictly they profess the written letter,
they are but imperfect, superficial, ineffectual believers,
who hold to the external part and experience not the internal.
These are Christians in name, but not in deed and in truth.
It is essential for us who have the Scriptures to believe both in the outward coming,
and in the inward ministration of our Savior; resigning all to Him,
and trusting in Him with that "`faith which is of the operation of God,`"^
footnote:[Colossians 2:12]
which works by love to the purification of the heart,
and is the saving faith of the gospel.

Complete Christianity has both an inside and an
outside--a profession or bodily appearance,
and a life and virtue, which is like a soul to that body.
Those who are in possession of both are complete Christians.
Those who have the inward part without the outward, though incomplete in that respect,
will, in the sight of perfect equity,
certainly be preferred to such as have the outward without the inward.
And indeed, in the case of those who have the history,
and profess the Christian religion, yet walk contrary to its requirings,
I believe it would be better for them in the end were they able to change
conditions with those conscientious Gentiles who had not the Scriptures.
Let such as these duly consider the following text.
"`Verily I say unto you, I have not found so great faith, no not in Israel;
and I say unto you, that many shall come from the east and west,
and shall sit down with Abraham, and Isaac, and Jacob in the kingdom of heaven;
but the children of the kingdom,`"
(who are children by education only)
"`shall be cast out into outer darkness, where there shall be weeping and gnashing of teeth.`"^
footnote:[Matthew 8:10-12]

Real Christianity consists not in the outward
profession of any framed articles or beliefs,
nor in the practice of signs and ceremonies,
however they may be displayed with pomp and zeal,
or whatever significance may be attributed to them by their supporters.
Form and profession do not make a real Christian,
but rather _the putting on of a new nature._
"`They that are Christ`'s, have crucified the flesh with its affections and lusts,`"^
footnote:[Galatians 5:24]
and, "`If any man be in Christ, he is a new creature; old things are passed away,
behold all things are become new, and all things are of God.`"^
footnote:[2 Corinthians 5:17-18]
The necessity of true regeneration, the power by which it is effected,
and the cooperation of God and man therein, are all included in this text:
"`If you live after the flesh, you shall die; but if you, through the Spirit,
do mortify the deeds of the body, you shall live.
For as many as are led by the Spirit of God, these are the sons of God.`"^
footnote:[Romans 8:13-14]

This new birth is not brought forth in man imperceptibly.
The new man is "`renewed in knowledge,`"^
footnote:[Colossians 3:10]
in certain and sensible experience.
The soul in whom this is going forward has an
internal sense of it through its whole progress,
and must keep a steady eye thereunto that it may continue to go forward.
"`We all,`" says the apostle, "`with open face,
beholding as in a glass the glory of the Lord,
are being transformed into the same image from glory to glory,
even as by the Spirit of the Lord.`"^
footnote:[2 Corinthians 3:18]
By looking at the deceitful beauty of temptation, man falls into and grows in sin.
But by keeping a steadfast eye inwardly unto Christ in spirit,
with humble resignation to Him and earnest desire after Him, man finds preservation,
and gradually advances from one degree of grace to another.
This continues until he really experiences a
renewal of the divine likeness upon his soul,
and an inward translation out of sin, darkness, and death, into divine light,
life and holiness; and thereby a change from anxiety and misery to peace and felicity.

The natural man may polish and adorn himself with a variety of literature, arts,
and breeding; but even in his best accomplishments,
he is but the natural man still--a man whom the apostle declares,
"`receives not the things of the Spirit of God, neither can he know them.`"^
footnote:[1 Corinthians 2:14]
This is the natural condition of all men before the work of renovation is begun in them.
Therefore, seeing all stand in need of divine grace to effect this,
and knowing that "`God desires all men to be saved and
to come to the knowledge of the truth,`"^
footnote:[1 Timothy 2:4]
so it is that "`the grace of God that brings salvation has appeared to all men,
teaching us`"--by its convictions--"`that denying ungodliness and worldly lusts,
we should live soberly, righteously, and godly in this present world.`"^
footnote:[Titus 2:11]
Thus, "`The Mighty One, God the Lord, has spoken and called the earth,
from the rising of the sun to its going down.`"^
footnote:[Ps. 50:1]
Indeed, the writings of the prophets and the apostles have never reached as
universally among mankind as this grace and power of God.

Christ was given "`as a covenant to the people,
as a light to the Gentiles`"...and "`as God`'s salvation to the ends of the earth.`"^
footnote:[Isaiah 42:49-6:6]
Not only does He offer His grace universally and individually,
but He even "`waits to be gracious.`"^
footnote:[Isaiah 30:18]
"`Behold,`" says He, "`I stand at the door and knock.
If any man hears My voice, and opens the door, I will come in to him,
and will sup with him, and he with Me.`"^
footnote:[Revelation 3:20]
When "`Judas (not Iscariot) said to Him, '`Lord,
how is it that You will manifest Yourself to us,
and not to the world?`' Jesus answered and said to him, '`If anyone loves Me,
he will keep My word; and My Father will love him,
and We will come to him and make Our home with him.`'`"^
footnote:[John 14:22-23]
This is Christ in Spirit, who proclaims, "`He that has an ear let him hear.`"^
footnote:[Mark 4:23-9; 7:16, etc.]

[.discourse-part]
Question: But if man in his fallen state is dead, how can the dead hear?

[.discourse-part]
Answer: When the Savior called, "`Lazarus, come forth!`"^
footnote:[John 11:43]
the dead man was quickened and immediately obeyed.
The voice of Him who is a "`life-giving Spirit`"^
footnote:[1 Corinthians 15:45]
has life-giving power.
"`The hour is coming, and now is, when the dead shall hear the voice of the Son of God,
and they that hear shall live.`"^
footnote:[John 5:25]

[.discourse-part]
Question: What is meant by His standing at the door?

[.discourse-part]
Answer: His wonderful condescension, patience, and long forbearance,
in waiting upon the soul of man for an entrance.
Christ desires that all men be prevailed upon to
willingly open their hearts to their Redeemer.

[.discourse-part]
Question: How does Christ in Spirit knock, or call?

[.discourse-part]
Answer: By influencing the soul in its seasons of quiet and stillness,
so as to stir up inclinations and desires towards what is good and true;
and at other times,
by distressing the soul with the painful sensations of
guilt and remorse for its sinful pursuits and practices.

[.discourse-part]
Question: How shall man open to Him and receive Him?

[.discourse-part]
Answer: By resigning his attachment to self,
and the propensities and pursuits of his carnal senses, and humbly adhering to the voice,
or present manifestations of the Spirit.

[.discourse-part]
Question: How does the Lord come in and sup with man,
and make him a partaker of His supper?

[.discourse-part]
Answer: When the Spirit of Christ is received by the soul in faith, love,
and due submission,
He proceeds by degrees to set it at liberty from the bondage and influence of corruption;
for, "`where the Spirit of the Lord is`"--in experience and possession--"`there is liberty.`"^
footnote:[2 Corinthians 3:17]
And when Christ has brought the soul into a proper degree of purification,
He sheds abroad the comfort of His love into it,
and makes it a partaker of the communion of saints, which is inward and spiritual.
This is the true supper of the Lord.
He who partakes of this, discerns and tastes the Lord`'s spiritual body,
and experiences it to be food indeed, and His blood to be drink indeed.
