== Chapter 5. A Birth of Divine Life in the Soul

Mankind is not left to Satan, nor to his own lusts,
nor to live without God in the world.
A way is cast up.
A means is provided.
God has sown a divine witness in the heart of each individual,
which will truly manifest right and wrong in the
consciences of those who faithfully attend to it,
affording both light and power to set them free from the mists of prejudice and lies,
and becoming to them a safe conductor,
and an able supporter in the paths of righteousness and truth.
What other instructor is equal to this most intimate witness?
A monitor so near, so constant, so faithful, so infallible!
Indeed, this is the great new covenant privilege of every man--
to hear the gospel preached day by day in his own heart,
without money and without price, yet with certainty.

Now, is it reasonable to conclude, that this kind, true, and penetrating discerner,
should be less than divine?
Can any person, upon serious consideration,
imagine this to be the nature of the fallen man himself?
Is it possible that a nature so corrupt and clouded,
should so clearly and instantly distinguish between good and evil?
And would the heart of man (which is declared by inspired Scripture to be
"`deceitful above all things, and desperately wicked`"^
footnote:[Jeremiah 17:9])
so faithfully reprove itself?
Would that which delights in its own indulgence, and is impatient of restraint,
act as a daily control against its own inclinations?
Is it the property of evil to do good?

Now consider: that which is natural leads according to nature;
that which is spiritual according to the Spirit.
These are distinguished in Scripture by the terms flesh and spirit,
and are truly said to war against each other in man.
As sin wars against the Spirit to destroy the soul,
so the Spirit wars against sin to save the soul.
Now, you who depreciate and revile this inward witness
instead of embracing it in humility and thankfulness,
let me present the following question:
While you confess it distinguishes right from wrong in your own
breasts by its approbation of the first and condemnation of the last,
can you thus acknowledge it to be infallibly good,
and at the same time attribute it to yourselves?
"`I know,`" says Paul, "`that in me, that is in my flesh,`"
or belonging to my nature, "`dwells no good thing.`"^
footnote:[Romans 7:18]
Is your nature in a better condition than his was?
Is there any good thing in yours, though there was none in his?
He confessed he had none as man.
I presume you have no more than he had.
From where, then,
comes this quick and righteous discriminator that appears in your consciences?
You will not say it is of Satan; it must therefore either be of man or of God.
For the reasons above mentioned, it cannot be of man; it must therefore be of God.
Wonderful is the mercy, and great the advantage to every man, that God himself,
according to the Scriptures, thus condescends to be the Teacher of His people,
by the manifestation of His Spirit in every heart.
Certainly, this inward witness ought to be accepted and observed
with the greatest reverence and thankfulness.

The operation and increase of this living Spirit
becomes a new life in and to the obedient soul,
quickening and refreshing it with a sense of divine love, strength, and comfort.
This life, being begotten and brought forth by the Holy Spirit in the willing mind,
is called a _birth_ of the Spirit;
and seeing that our first parents were favored with
this spiritual birth immediately upon their creation,
but lost it by disobedience,
the renewal of it has been termed _regeneration_ and _renovation,_
or the birth of divine life renewed in man.
Being inheritors of spiritual death in Adam, or in the fallen state and nature,
we can only be born again to life in Jesus Christ by
the power and virtue of His Holy Spirit,
who is the resurrection and the life.

Every reproductive power brings forth its own likeness--the evil spirit an evil birth,
and the good spirit a birth corresponding to its own goodness.
And as every natural birth allows for a growth, so does this spiritual birth in the soul.
Our Savior represents its gradual progress with the
analogies of the increase of the mustard seed,
the process of leaven, the springing up of living water unto everlasting life, etc.
The apostles Peter and John also show that there are
several gradations experienced amongst believers,
using the metaphors of new-born babes, children, young men, and fathers,
and surely even the state of fathers allows for continual advances,
as Paul himself bore witness.
For though Paul truly asserted that the law of the Spirit of life in
Christ Jesus had set him free from the law of sin and death,
yet he was sensible of higher degrees of attainment still before him,
and after nearly thirty years in the apostleship he makes this
acknowledgment--"`Not that I have already attained,
or am already perfected; but I press on,
that I may lay hold of that for which Christ Jesus has also laid hold of me.
Brethren, I do not count myself to have apprehended; but one thing I do,
forgetting those things which are behind and
reaching forward to those things which are ahead,
I press toward the goal for the prize of the upward call of God in Christ Jesus.`"^
footnote:[Philippians 3:12-14]

Those who consider the necessity of man`'s being regenerated, transformed,
and guided by the Spirit of his Maker an insult to human reason,
give great dishonor to Supreme wisdom, goodness, and power.
The dignity of human nature does not at all consist in self-sufficiency.
The most exalted of angelic beings neither wills nor acts independent of their Creator;
much less man, who in his primitive purity was "`made lower than the angels.`"^
footnote:[Ps. 8:5]
Indeed, man stands in continual need of divine help;
and his true dignity consists in his being
capable of _consciously receiving_ that assistance,
and of thereby having access to, and preservation in,
a blessed union and communion with his Maker.
It is no disparagement to an inferior to be directed and guided by a Superior Being;
especially by the supreme Lord, and sole Author of all existence!
Endowed with His Spirit, in any degree,
the creature is raised above the highest elevation of its own nature;
and the more it is clothed with Him, the more it is dignified and exalted.
Truly, it is only when the Sun of Righteousness sheds forth
His life-giving beams upon the spirit of man,
that the poor worm is made able to take wing and mount above his earthly limits,
towards the regions celestial.
