== Chapter 6. Regeneration--A Discernible Experience

Now, man, what is the great business of your life in this world,
but to return to the paradise of God,
and to secure an everlasting inheritance which is incorruptible, undefiled,
and fades not away?
To accomplish this, you must be stripped of all that makes you unfit for an entrance.
Whatever has been the cause of exclusion must be removed.
Whatever can have no place or habitation there, must be separated from you,
or you cannot be admitted.
"`That which restrains will restrain till it be taken out of the way.`"^
footnote:[2 Thessalonians 2:7]
Whatever you have in you or about you that you are attached to in consequence of
the fall--all separate self and the carnal mind--must be resigned,
or you can never know a restoration.
The gospel axe, the power of the Spirit of God,
must be laid to the root of the tree of corruption in you, that it may be uprooted,
and the Vine of life implanted in its place.
Then the implanted Word, which is able to regenerate and save the soul,
may flourish and bring forth its heavenly fruits where the sinful
nature has long spread its poisonous products in the heart.
From this alone arises all true happiness in the creature,
and living praises to the eternal Author of salvation.

The necessity of regeneration was not only preached to the people in the primitive times,
but was actually experienced by the believers.
We have a clear and significant instance in 1 Cor. 6: 9-11;
"`Do you not know that the unrighteous will not inherit the kingdom of God?
Do not be deceived; neither fornicators, nor idolaters, nor adulterers, nor homosexuals,
nor sodomites, nor thieves, nor covetous, nor drunkards, nor revilers,
nor extortioners will inherit the kingdom of God.
And such were some of you.
But you were washed, but you were sanctified,
but you were justified in the name of the Lord Jesus and by the Spirit of our God.`"
Here the apostle plainly testifies that some of the Corinthian brethren,
who had been of polluted hearts and vicious lives, were become regenerated,
made clean and holy;
and he shows that this great change in them was
wrought in the name (or power) of the Lord Jesus,
which he explains to be by the Spirit of our God.
The apostle Peter concurs with Paul in bearing the like testimony--"`Seeing
you have purified your souls in obeying the truth,
through the Spirit, unto unfeigned love of the brethren;
see that you love one another with a pure heart fervently; being born again,
not of corruptible seed, but of incorruptible,
by the Word of God which lives and abides forever.`"^
footnote:[1 Peter 1:22-23]
Many other texts might be added to the same purpose.

The apostle particularly shows the nature and manner of
this work in the 7th and 8th chapters of Romans,
which, for lack of a real experience,
many have been led to imagine were intended by him to be
descriptive of his own condition at the time he wrote them.
Nevertheless, it is manifest that these chapters comprehend diverse,
and even contrary conditions,
which he and others had experienced in their Christian progress,
and which it was impossible he should be in at one and the same time, namely:
a state of darkness and a state of light; a state of uncleanness and a state of purity;
a state of bondage and a state of liberty; a state of life and a state of death.

In chapter 7:5, he says,
"`For when we were in the flesh,`"--under the dominion of the
carnal nature--"`the sinful passions which were aroused by the
law were at work in our members to bear fruit to death.`"
Here he refers back to that state of sin and death they had formerly been enslaved in,
but were now past, as fully appears by the succeeding verse, which says,
"`But now we have been delivered from the law, having died to what we were held by,
so that we should serve in the newness of the
Spirit and not in the oldness of the letter.`"
In verse 7, he returns to the former state again, and becomes more particular:
"`I had not known sin,`" says he, "`but by the law.`"
Before he became sensibly convicted in his own conscience,
where a sense of the requirement of God was opened to him,
he remained in his first state of natural blindness, yet knew it not to be such,
despite his learned education and legal strictness.
Though "`dead`" as to any sense of divine life,
yet he was "`alive`" in the spirit of the world.
"`For,`" says he,
"`I was alive without the law once; but when the commandment came,
sin revived and I died.`"
Now opposed by the appearance and internal administration of the spiritual law,
which brought true conviction,
the sinful nature was freshly excited by the power of evil,
and sprung up as with new life and vigor to obstruct his escape from it;
"`for without the law sin was dead.`"
That is to say, the nature of sin remained quiet and undisturbed,
enjoying its indulgence without interruption,
until the law of life was administered against it.
Then "`the commandment which was ordained to life, I found,`"
by its resistance of that nature, "`to be unto death.
For sin taking occasion by the commandment, deceived me,
and by it slew me,`" or darkened me, and brought a sense of death over me.

Sin seems to have deceived him at first into a belief that the law brought forth death,
because he felt a sense of death ensue upon the convictions of this law.
But, in truth, death is the fruit of sin, which is condemned by the law.
So he says, "`The law is holy, and the commandment holy, just, and good.
Was then that which is good made death unto me? God forbid!`"^
footnote:[Romans 7:12-13]
Rather, he found it was that which so violently opposed the law that produced death,
and occasioned the condemnation of the law to come upon him,
which uncovered this death in him.
This was permitted that "`sin might appear sin,`" and that by the convicting
force of the commandment it might become "`exceedingly sinful`" in his view,
and be held by him in abhorrence.

He then feelingly expresses the trapped situation of this convicted,
but unchanged state, vs. 14--
"`The law is spiritual, but I am carnal, sold under sin.
For what I am doing, I do not understand.`"
I am convinced it is evil, and would gladly be delivered from it;
but despite my convictions, I am under its power, and unable to extricate myself.
"`For the good that I will to do, I do not do;
but the evil which I will not to do, that I do.`"
Yet, in patient submission and fervent cleaving to God,
some consolation and understanding attends this awakened condition;
"`For if I do what I will not to do, it is no longer I that do it,
but sin that dwells in me.
For I delight in the law of God according to the inward man;
but I see another law`"--or power--"`in my members, warring against the law of my mind,
and bringing me into captivity to the law`"--or power--"`of sin which is in my members.`"
Thus prevented from what I love, and taken captive by what I hate,
what a miserable slavery I am in!
"`O, wretched man that I am! Who shall deliver me from the body of this death?`"

In conclusion, he proceeds to show that, though this had once been his condition,
he now experienced perfect deliverance from all
the perplexing and afflicting circumstances,
and the several exercising states he had formerly passed through.
"`There is therefore,`" says he,
"`now no condemnation to them which are in Christ Jesus,`"
(though previously there clearly was)
"`who walk not after the flesh,
but after the Spirit; for the law of the Spirit of life in Christ Jesus,
has set me free from the law of sin and death.`"^
footnote:[Romans 8:1-2]
This again testifies his deliverance, and corresponds to the verse previously cited,
"`Now we have been delivered from the law,`" which condemns for sin;
"`having died to what we were held by +++[+++i.e. the sinful nature+++]+++,
so that we should serve in newness of the Spirit, and not in the oldness of the letter.`"
Col. 1:13-14 is in agreement with these Scriptures: "`Giving thanks unto the Father,
who has made us fit to be partakers of the inheritance of the saints in light,
who has delivered us from the power of darkness,
and has translated us into the kingdom of His dear Son.`"

In the passages above cited from Romans 7 and 8,
the experienced apostle evidently includes a
representation of three very different conditions,
showing their course of progress and their differences one from another.
First, a natural, blind, and un-convicted state, which is that of darkness and death,
corresponding to the original chaos before light was brought forth.
Second, a state of illumination and discovery, of conviction and internal warfare,
with a view to complete conversion.
This state partakes of a mixture, where light and darkness are in the act of separation,
like that in Gen. 1:3-5. Third, a state of redemption from the power of sin,
through purification, and a translation into the spiritual kingdom of Christ.
This is the state of the perfect Christian, and completes the new creation,
wherein everything takes its due place and moves in its proper order.

I now appeal to the reader--is it not an absurdity to imagine that these three diverse,
and in some respects contrary,
states should all subsist together in the same person at the same time?
In this short section of his letter
(containing a brief but comprehensive sketch of the work of the new-birth),
the apostle shows the young in the faith what different states
they have to pass through in their preparatory travel,
and also reminds the truly regenerate what they have already witnessed,
in the words of his own experience.
He describes the various steps and principal leadings of the Holy Spirit,
till by its effectual operation the soul is rendered a new creature,
and an entrance is abundantly supplied into the kingdom of God; which,
being inward and spiritual, is entered by an inward and spiritual way.

Hence it is clear, that a man may acquire all the learning,
and receive all the degrees that schools and colleges can bestow,
with all the authority men can afford him,
and may also be strict in the practice of all the forms and exteriors of religion,
and yet remain a natural man still.
Indeed, such things can bring him no nearer to true regeneration than
he was at the moment of his natural birth;
for the new-birth is the work of the Holy Spirit alone.
Nothing but the Spirit of holiness can make a man holy;
for nothing can communicate or impart what it does not have.
Nothing can set men free from the power of sin
(and its wages of death)
but the law or power of the Spirit of life in Christ Jesus,
individually administered.
This Holy Spirit--which turns sinners into saints by a real purification,
and renders them new creatures,
as to their inward state--is the soul`'s true light and leader.
By its immediate manifestations in the heart,
the Spirit becomes the primary guide of life and conduct,
and also frequently brings Scripture truths to remembrance,
opening their meaning profitably to the understandings,
and influencing the mind and heart to live in accordance to God`'s revealed truth.

It is evident that the apostle, in the foregoing scriptures,
describes diverse changes of condition which,
through the operation and effect of the Holy Spirit,
he had certainly known and sensibly felt.
Nevertheless, there are many in Christendom, even amongst the leaders of the people,
who discount all such inward and individual experiences
of the Spirit as enthusiasm or distempered fancy.
Alas, these make a show of knowledge by talking about the things of God,
but are without any right understanding of them;
for truly the pomp of natural learning and the ornament of eloquence
have no more concord with the Truth than does the pride of life.
These things belong to the wisdom of this world, by which God is not to be known;
"`For the world, by its wisdom, knew not God,`"^
footnote:[1 Corinthians 1:21]
nor the things of God.
All the knowledge of the natural man,
the man whose nature remains unchanged (whether called Pagan, Jew, or Christian,
and whether his knowledge be called philosophy or divinity),
is but the ineffectual wisdom and head-knowledge of this world;
it is not the wisdom from above by which alone God, and the things of God,
are known and experienced.
God`'s wisdom is out of the reach of man`'s arts, languages, and sciences,
and is discovered only by the manifestation of the Spirit of Christ in the
heart,--"`In whom are hidden all the treasures of wisdom and knowledge.`"^
footnote:[Colossians 2:3]

Yet though the world, through all its admired and celebrated wisdom, does not know God,
there is a wisdom communicated to man by which He is known.
"`For God,`" says holy Writ, "`who commanded the light to shine out of darkness,
has shined in our hearts,
to give the light of the knowledge of the glory of God in the
face`"--or inward appearance--"`of Jesus Christ.`"^
footnote:[2 Corinthians 4:6]
The apostle adds,
"`We have this treasure in earthen vessels that
the excellency of the power may be of God,
and not of us.`"^
footnote:[2 Corinthians 4:7]
This luminous and excellent power operates upon the humble,
thankful recipient so as to open an understanding of what he reads,
both in Scripture and in other experiential writings,
often giving him to _feel_ what he reads, and to reap its improving effects.
But he who rejects the means can never attain the end.
He who refuses or flees from the light of life when it offers itself
to him by reproof and conviction (not believing it to be of God,
nor receiving it as such), stops its operation,
and prevents it from opening to him and enlarging in him.
The unbelieving heart shuts up its own way,
and therefore remains insensible of the internal power of the Savior.

What man upon earth can say he has not had convictions?
And who can have a sense of them and not distinguish
them from the efforts of his own reason,
not distinguish the Reprover from the reproved?
Unfelt convictions are impossibilities.
Can the work of renovation be known without any perception of its progress?
Did the apostle Paul so feelingly describe the painful states he had travelled through,
and the opposing powers engaged within him, without ever having a certain sense of them?
Are his Christian experiences to be treated as the mere
product of an enthusiastic or distempered fancy?
How could a person witness repentance unto life, remission of sins,
and "`times of refreshing from the presence of the Lord,`"^
footnote:[Acts 3:19]
without an inward sense of them?
Were all the cries,
the pantings and thirstings after the divine presence uttered
by the sacred writers without a deep sense of their lack?
And were all their triumphant rejoicings in the consolation of
His presence expressed under a total insensibility of it?
Were the fruits of the Spirit and the comforts of the
Holy Ghost unfelt by those who enjoyed them?
Who can affirm these absurdities?
To where can such blind leaders bring their blind followers?
Those who turn their backs on the light must walk in darkness.
It is the sole property of the Spirit of Christ, the Light of men,
to make true discoveries to the soul,
both respecting itself and everything else that concerns it.
Hence He is rightly called the "`Sun of Righteousness`"^
footnote:[Malachi 4:2]--for He is the same thing to the soul
of man that the sun in the firmament is to the body.
The one is the light without, the other the light within.

It is the unbelieving and unrenewed man,
unacquainted with the effectual operation of this heavenly Spirit,
that unknowingly rejects and disparages it,
and thereby contributes to keep both himself and others in blindness concerning it,
and prejudice against it.
"`The natural man,`" says the apostle, "`receives not the things of the Spirit of God,
for they are foolishness unto him; neither can he know them,
because they are spiritually discerned.`"^
footnote:[1 Corinthians 2:14]
'`What?`' says the mighty man of reason, '`Must I put out my eyes in order to see?
Must I lay aside and renounce my reason to obtain a better understanding?
It is impossible and preposterous!`'
No, it is not _right_ reason that is objected to and advised against;
for right reason is true,
and ever corresponds with the inward motions of the Spirit of Truth.
However, it evidently appears
(from the various biases, presuppositions, weaknesses,
and irreconcilable differences among men)
that _human_ reason is often far from being agreeable to _right_ reason.
What is cautioned against, therefore,
is the setting up of human reason above its due place in religion,
making it the leader instead of the follower of revelation,
the teacher instead of the learner, and esteeming it with any kind of self-sufficiency,
independent of the direction and help of God`'s Holy Spirit.

As the light of the sun is so perfectly dispensed by sovereign
wisdom in such a way that does not blind men`'s eyes,
but rather assists in the proper use of them;
so too divine illumination and influence is administered by the same wisdom,
in such due degrees, that it neither banishes man`'s reason,
nor deprives it of its utility,
but restores it to its proper use in religion by
dispelling the fogs of prejudice and passion,
giving it a clear sense of duty, and furnishing ability to perform it.
The holy men of God were not deprived of their understandings when
they spoke and wrote as they were moved by the Holy Spirit.
Rather, they found their understanding illuminated and highly improved by it.
They were not used by the Spirit as senseless machines or irrational vegetables,
unaware of the virtue arising in and empowering them.
Their faculties were brightened and raised to a higher pitch of usefulness than
could ever have been experienced while unassisted by the power of divine grace.
With good reason, therefore,
has one of the inspired writers given this necessary exhortation:
"`Trust in the Lord with all your heart, and lean not to your own understanding.`"^
footnote:[Proverbs 3:5]
And he further says, "`He that trusts in his own heart, is a fool.`"^
footnote:[Proverb 28:26]
