== Chapter 7. The Law of the Spirit of Life in Christ Jesus

Though many are taught to imagine an importance
and an efficacy in various outward ceremonies,
signs, and shadows of the legal dispensation, it is nevertheless certain that,
"`In Jesus Christ, neither circumcision avails anything, nor uncircumcision,
but faith which works by love.`"^
footnote:[Galatians 5:6]
Indeed, neither the practice, nor the neglect,
of forms and rituals avails anything with God--though the
former may unprofitably busy those who practice them,
and dangerously deceive them so as to place confidence either in their own performances,
or in those of their leaders.

The religion of the true Christian consists not in outward form, but in substance,
and arises not from the activity of human reason, imagination, or opinion,
but from the heartfelt sensation of divine love in the Light of life.
Its foundation is no less than the immediate administration of
God`'s Holy Spirit to the spirit of man.
This Spirit shows unto man God`'s thoughts about him,
and reveals who and what the Lord is, so far as concerns the believer.
It opens the understanding and directs the duty of the obedient;
"`For the way of man is not in himself;
it is not in man who walks to direct his own steps.`"^
footnote:[Jeremiah 10:23]
It is the light of the Lamb which shows the way of salvation,
the one great Light appointed to rule the day (or
spiritual dispensation) of Christianity,
in which those who are saved must walk.

Men in their natural state may, by reading and study,
collect an abundance of notions concerning the Supreme Being;
but even as light reveals all things,
and yet cannot be really known except by its own appearance, so God
(who, in the most perfect sense, is light)
can only be truly known by His own immediate manifestation.
What men normally call the knowledge of God is
but a series of notions concerning His essence,
His attributes, and His providence.
But what our Savior called the knowledge of God,
is the _real experiential sense of His life._
"`This is eternal life, that they might know You, the only true God,
and Jesus Christ whom You have sent.`"^
footnote:[John 17:3]
To truly know Him is to participate in the quickening sense of His life,
through the communicated influence of His eternal Spirit.
Thus the true knowledge of God is a partaking of the new covenant,
or true gospel dispensation; for therein it is declared,
"`They shall all know me, from the least of them to the greatest of them.`"^
footnote:[Jeremiah 31:34]

Accordingly,
the truly living Christian has a certain sense of divine life in his own breast,
which affords him instruction, strength, and comfort,
in such a manner that he waits in faithfulness upon it,
and is under no absolute necessity to lean upon the teachings of other men.
However, when teachers come in a degree of the same life,
he feels them and accepts them as instrumentally from God.
This life of God in Christ is the very soul of Christianity,
without which the best forms and highest professions
are but as undesirable members of a dead body.

"`He that has the Son has life, and he that has not the Son of God has not life.`"^
footnote:[1 John 5:12]
"`Because I live,`" He says, "`you shall live also.
In that day, you shall know, that I am in my Father, and you in me, and I in you.`"^
footnote:[John 14:19-20]
It is because He lives, and communicates of His life to His spiritual followers,
that they live also.
Of these the true church--the adopted body of Christ under all denominations--is composed.
These alone are His peculiar heritage and priesthood.

The body of Christ is a living body, rendered such by the inspiration of His life.
He Himself is the life common to all His true members,
and by His vital influence He communicates a living sense of truth to them,
inclines them to Himself,
and inspires them both with the desire and the power of obedience.
And as these advance in faithfulness,
He favors them with increasing tastes of divine grace and love,
the sweet savor of the holy anointing,
and the indwelling virtue and glory of His heavenly presence.
"`There is one body, and one Spirit.`"^
footnote:[Ephesians 4:4]
If there was not one and the same Spirit throughout the whole church,
it could not be one body, nor a living body.
"`The body of Christ cannot live but by the Spirit of Christ,`" says Augustine.
He who partakes not of the same Spirit with the Head,
is no true member of the body.
His spiritual influence is the precious blood or spring
of life which renders all His members living.
And He who gives life, gives also a sense of that life,
which life is "`hidden with Christ in God`"^
footnote:[Colossians 3:3]--hidden from the
knowledge of those who remain unquickened by it;
and from this arises all their opposition to it.

We are all by nature strangers to this divine life,
and we cannot by any means obtain it for ourselves.
It is not of man`'s acquirement, but of God`'s communication;
thus it is as far out of the reach of the most learned as it is the most illiterate.
It is hidden from the wise and prudent in their own eyes,
and revealed to those who are as babes to the world`'s wisdom.
It is not the high and learned, but the low and humble that God teaches,
and the meek that He guides in the paths of truth and judgment.
Everyone`'s eye, therefore, ought to be turned humbly to God alone,
and not to be fixed upon the wise, the scribes, and the disputers of this world;
for God has, by the powerful simplicity and purity of His gospel dispensation,
"`made foolish the wisdom of this world.`"^
footnote:[1 Corinthians 1:20]
Yet so fond is the world of its own wisdom, that it has, in great measure,
pulled down the cross of Christ, together with true spiritual religion,
and erected and supported the present idol in its place.
Before this image the world has bowed down, and indeed it has been a means to blind,
ensnare, and deceive its worshippers, whose faith stands in the wisdom of men,
and not in the power of God.

From a due consideration of the exalted purpose for man`'s creation,
as well as the debased and corrupt state of mankind since the fall,
it must evidently appear that _true regeneration_ has ever been
the one thing needful--a work essential for all to experience.
And as the birth of the Spirit cannot be brought forth by anything but the Spirit,
so its growth and accomplishment must also be preserved by the Spirit.
Hence the abiding, or indwelling of the Spirit,
is of absolute necessity to the regenerate,
that as their souls are quickened into the divine life by it, they may continue to live,
move, and have their being as Christians therein,
and be sustained in a spiritual union and blessed communion with their Maker.

The essence of true religion has ever been the same,
primarily consisting in the life of God being raised up,
and the love of God shed abroad in the heart, operating therein unto true renovation,
and towards every virtuous and benevolent fruit.
Whatever externals or ceremonies that have, at various times,
been super-added by divine direction or command,
were not intended to alter or unsettle men from due and constant attention to vital,
spiritual religion.
It was only as man became greatly degenerated from the inward and spiritual,
and darkened concerning it,
that the merciful Creator was pleased
(by means suited to their estranged and carnal condition)
to point it out to them and lead them by signs and symbols towards it.
Thus the Mosaic law was not meant to be the whole of religion to the Israelites,
or to supersede the internal religion of Abraham,
but only to be as "`a schoolmaster to bring them to Christ`"^
footnote:[Galatians 3:24]
in Spirit, in whom all is included and fulfilled,
and whose presence was then with the faithful in Israel,
who had spiritual communion with Him.
For, according to Scripture, "`They did all eat the same spiritual meat,
and did all drink the same spiritual drink;
for they drank of that spiritual rock that followed them; and that rock was Christ.`"^
footnote:[1 Corinthians 10:4]

It is a vain thing to imagine that religion ever
wholly consisted in outward modes or forms,
or that the Lord at any time dispensed with the inward
substance for the sake of the outward shadow.
No; He is God and changes not.
His law is His own Spirit of eternal perfection.
The different modifications that God has used among men in points of religion have
been occasioned by the different alterations in the conditions of mankind.
The all-wise God has directed some for a time, in condescension,
to outward shadows and ceremonies for the good end above-mentioned;
and men have invented and added an abundance more,
according to their own carnal misapprehensions of spiritual things,
or to advance their own sinister purposes.
But exterior forms are but temporary matters;
they are not the essence of true Christianity.
The great Author of Christianity represents it as
"`a well of water in man springing up into everlasting life.`"^
footnote:[John 4:14]
It arises from a living, abiding, increasing Spirit in man,
which is of a pure and heavenly nature.
As this is cordially embraced, it enlarges in the soul,
expels the works and power of darkness, and produces its own genuine fruits of humility,
self-denial, patience, righteousness, holiness, meekness, gentleness, temperance,
goodness, brotherly-kindness, love, resignation to God, and trust in Him alone.
It derives its origin from heaven, and leads back to heaven,
carrying the soul out of all formalities and false rests, up to the Supreme good Himself.
It breaks down all self-will, and brings into perfect resignation to the divine will.
In this humble and contrite frame (and in no other) we can sincerely and truly say,
"`Your kingdom come; Your will be done!`"^
footnote:[Matthew 6:10]
For while our wills stand in separation from the will of God,
we cannot address Him in these terms with propriety, or in Spirit and truth.

Now, the pride of man is naturally hostile to this abased and broken condition.
It knows not how to submit to be nothing, or to think itself nothing,
though indeed it is worse than nothing.
It would eagerly set up and exalt itself as possessing importance, estimation,
and merit of its own; yet all its pretenses are false and vain.
In truth, man is nothing but what God has made him,
and possesses nothing but what God affords him.
He is wholly God`'s, and not his own,
and is therefore bound in duty to walk in obedience to Him every moment of his life,
which is given him for that purpose.
And seeing that man has fallen short of his duty,
and has sinned against his Creator by disobedience, it is not in his power,
by anything he can perform, to merit heaven, or to purchase remission for himself.
He can neither undo what he has done,
nor render to his Maker an equivalent for the trespasses he has committed against Him.
But such is the merciful goodness, and free grace of God towards His helpless creatures,
that He offers both forgiveness and felicity upon the most reasonable terms.
To the "`willing and obedient,`"^
footnote:[Isaiah 1:19]
to him "`who is faithful unto death,`"^
footnote:[Revelation 2:10]
to "`him that overcomes`"^
footnote:[Revelation 2:11,17,26,7; 3:5, 12, 21; 21:7]
(through the power of the Spirit), are the promises of eternal life.
Upon the foundation of these free and voluntary offers of divine goodness,
and man`'s compliance with the conditions, stands his right of entry.
"`Blessed are they that do His commandments,
that they may have the right to the Tree of Life,
and may enter through the gates into the city.`"^
footnote:[Revelation 22:14]

In Scripture, the laws and requirements of God to man are often called covenants.
The man in covenant with God owes his very being, and all the good he receives,
spiritual and temporal, to his Maker, to whom he stands indebted for all.
God, therefore, has an unquestionable right to claim all of man`'s affection, gratitude,
and obedience,
and more especially since all of His dealings contribute to man`'s everlasting advantage.
There is also an internal,
spiritual covenant--a divine connection or union--which the heart of
man comes to feel as he grows in faithfulness to his Creator.
This is the Spirit of life in Christ Jesus,
which sets the soul free from the bonds of sin and death,
and unites it to its Savior in the powerful covenant of divine love.
By this, through faith, the soul becomes engrafted into Christ,
and by obedience it remains in Him as a branch in the vine;
for "`he that is joined unto the Lord is one spirit.`"^
footnote:[1 Corinthians 6:17]
Of this vital union regenerate souls have a certain awareness
and understanding in proportion to their progress.
"`Hereby know we that we abide in Him, and He in us,
because He has given us of His Spirit.`"^
footnote:[1 John 4:13]--"`By this we know that He abides in us,
by the Spirit which He has given us.`"^
footnote:[1 John 3:24]
Hence it is clear,
that the gift of the Spirit communicates this understanding to the soul.
