== Chapter 8. Internal and Eternal Religion

Evident tokens of internal religion,
and the immediate manifestations of the Spirit for that end,
appear throughout both the Old Testament and the New.^
footnote:[Editor`'s Note:
Though Early Quakers maintained that a measure of the Spirit
was at work in seeking hearts ever since the fall of mankind,
they nevertheless held that a greater and fuller endowment of the
Spirit was "`poured out upon all flesh`" in the New Covenant.
William Penn explains that the Spirit "`was more
sparingly communicated in former dispensations,`" but,
beginning at Pentecost, "`the light that shined but dimly before, +++[+++was made to+++]+++
shine out of the darkness, and the Day-star began to rise in the hearts of believers,
giving unto them the knowledge of God in the face, or appearance, of His Son, Jesus Christ.`"
([.book-title]#A Brief Account of the Rise and Progress of the People Called Quakers,# Chap. 1)]
Before the flood, the old world was favored with the manifestation of the Holy Spirit,
as is implied in Gen. 6:3,
"`My Spirit shall not always strive with man,`"--or
rather "`in man,`" as the Hebrew ought to be rendered.
And indeed,
where else could the Spirit properly be said to strive with man other than in the soul,
where the seat of man`'s corruption is, and where all suggestions of evil are applied?
And to what end should the Spirit strive with them,
but to bring them to repentance and reformation, and to the experience of the kingdom,
or ruling power of God in them.

Renovation of the heart by the Holy Spirit,
and the genuine fruits of repentance towards God, faith in Him, and obedience to Him,
was also the principal and essential part of religion, even among the Israelites.
In Duet. 30:10,
Moses shows the conditions upon the performance of which they should be
entitled to the promises--"`If you obey the voice of the Lord your God,
to keep His commandments and His statutes which are written in this Book of the Law,
and if you turn to the Lord your God with all your heart and with all your soul.`"
These are the terms: First, that they should keep the law;
this was the external and legal part of their duty,
consisting largely in figures and testimonies of inward, spiritual religion.
Second, that they should turn their whole hearts and souls to God;
this was the internal and evangelical part of their covenant.
Moses does not leave them in a state of uncertainty,
but proceeds to show them to what their inward attention should be turned.
"`For,`" says he,
"`this commandment which I command you this day,`"--or that which I
command you to turn your heart unto--"`is not hidden from you,
neither is it far off.
It is not in heaven that you should say,
'`Who shall go up for us to heaven and bring it unto us,
that we may hear it and do it?`' Neither is it beyond the sea that you should say,
'`Who shall go over the sea for us and bring it unto us,
that we may hear it and do it?`' But the word is very near you,
in your mouth and in your heart, that you may do it.`"^
footnote:[Deuteronomy 30:11-14]

The apostle explains this passage in Rom. 10:6-8,
"`The righteousness which is of faith speaks in this way, '`Do not say in your heart,
who shall ascend into heaven?
(that is to bring Christ down from above);
or, who shall descend into the deep?
(that is to bring up Christ again from the dead).`'
But what does it say?
'`The Word is near you, even in your mouth and in your heart.`' That is,
the Word of faith which we preach.`"^
footnote:[Romans 10:6-8]
By this explanation of the apostle it appears:
_First,_ that in addition to the written law,^
footnote:[See Deuteronomy 29:1 where it is said,
"`These are the words of the covenant which the Lord commanded
Moses to make with the children of Israel in the land of Moab,
[.underline]#besides the covenant# which He made with them in Horeb.`"
(emphasis mine)]
Moses then preached to Israel the same Word of faith
which Paul and his evangelical brethren did.
_Second,_ that this Word is Christ Himself in Spirit,
calling for attention and obedience in the heart (or conscience) of man,
in order to effect his restoration and salvation.
And _third,_ that this refers not to location or time,
but is an inward visitation of the Savior of mankind by His Spirit in the heart.

The Word of faith is the Word of truth, the Word of the everlasting gospel,
and not a composition of letters.
The term _word,_ like many other terms, is used in various senses,
such as a speech or saying, a report, a command, an exhortation, instruction, etc.,
all of these being composed of words.
And even as men use words to convey their sense or meaning one to another,
so God conveys His sense to men by Christ,
who is peculiarly and emphatically called in Scripture the Word of God.
Moreover, just as words are received from the mouths of others by hearing,
so the manner by which the soul receives internal understanding, reproof,
etc. from the Holy Spirit, is metaphorically called hearing,
or "`the hearing of faith.`"^
footnote:[Galatians 3:2,5]
Thus faith, which is the gift of God, is said to
"`come by hearing, and hearing by the Word of God.`"^
footnote:[Romans 10:17]
That is to say (as I apprehend),
that the internal sense itself is opened in the soul by the Spirit of Christ,
and truth is there communicated by the same Spirit.

Hence we see that the Divine charge given to the Jews consisted not in the outward,
written law only; nor were they kept in ignorance of inward, spiritual religion,
or of a future state of rewards and punishments.
For, if it were so,
to what purpose did Moses press the consideration of
their latter end upon them with so much fervency?
"`O that they were wise, that they understood this,
that they would consider their latter end!`"^
footnote:[Deuteronomy 32:29]
Or, why would he command their attention to the living Word of faith (Christ in the heart),
as well as to the written code?
He was an eminently inspired prophet, and well knew that salvation comes by Christ alone,
and that His inward spiritual law is as preferable to
the exterior one as the substance is to the shadow.
Obedience to the outward, temporal law, had outward and temporal promises;
but obedience to the inward,
spiritual law has promises of an internal and eternal nature.
By the works of the first no man could be justified; but by the operation of the last,
sanctification is wrought, and salvation experienced.
Indeed, Moses was a type of Christ, and the temporal law, with its temporal rewards,
was a type of the law of the spirit of life in Christ Jesus, and its eternal recompense.

But it may be asked: if the spiritual law was always afforded,
what occasion was there for the addition of temporal statutes?
I answer, first: the Israelites,
by living under servitude to a most superstitious and idolatrous people,
had become prone to superstition and idolatry themselves.
"`They were mingled among the heathen,`" says the Psalmist,
"`and learned their works; and they served their idols, which were a snare unto them.`"^
footnote:[Ps. 106:35-36]
Out of this idolatry they were to be brought,
and by their obedience to the only true God,
they were to become an example to the nations around them,
to influence their return as well.
Though all had the Word near in the heart, yet having lost the right sense of what it is,
"`the law was added because of their transgression`"^
footnote:[Galatians 3:19]
and corruption, till the coming of Christ in the flesh.
Seeing that their deep and habitual attachment to the forms and
superstitions of paganism would not admit a full and immediate deliverance,
divine wisdom condescended to meet them in the state they were in,
and to proceed gradually with them,
allowing some forms and ceremonies which "`were copies of the heavenly things.`"^
footnote:[Hebrews 9:23]
Thus He made the outward law a temporary instrument to bring
them gradually towards that perfect religion which He intended
(in due season) to introduce and set up in its purity,
for all men to come into and walk in.

In the mean time, the sovereign wisdom was pleased to sound an alarm,
and set up a banner before the rest of mankind through
His involvement with the descendants of Israel.
He wrought wonders for their deliverance and support,
and besides the many excellent moral precepts,
He dispensed to them "`the form of knowledge and truth in the law,`"^
footnote:[Romans 2:20]
which symbolically denoted the nature and manner of redemption
and salvation through His Son by many significant types,
allegories, and similitudes.
These external representations were wisely adapted to a dark and superstitious people,
and were intended to serve as a schoolmaster to lead them gradually to Christ; that is,
to the knowledge of Christ--both in His outward appearance as
a propitiatory sacrifice for the sins of mankind,
and in His inward appearance as the hope of
glory and the true sanctifier and Savior of men.
For though they were all "`baptized unto Moses in the cloud,`"--or dipped into his
exterior dispensation as under a veil--yet the spiritually minded among them were
enabled to penetrate through the veil to the internal reality,
and as before observed, "`did all eat the same spiritual meat,
and drink the same spiritual drink;
for they drank of that spiritual rock that followed them, and that rock was Christ.`"^
footnote:[1 Corinthians 10:1-4]

Still further to assist them,
divine Goodness at times inspired many of the most regenerate
and devoted of both sexes with the spirit of prophecy,
and engaged them to preach the necessity of true righteousness and holiness.
These prophets often directed men to look _through_ the
figures and outward similitudes in the ceremonial law,
unto the truth or substance signified by them.
These plainly exhorted and pointed their hearers to an inward and spiritual religion,
which indeed was the ultimate intent of the Mosaic,
and every other dispensation of God to mankind.
For the rituals of the law were not instituted to supersede, but rather to serve,
as a pattern^
footnote:[Exodus 25:40-9; 26:30; Numbers 8:4; Acts 7:44; Hebrews 8:5]
of "`the law of the spirit of life in Christ Jesus.`"^
footnote:[Romans 8:2]

I do not apprehend that "`the mystery of godliness,`"^
footnote:[1 Timothy 3:16]
and its internal life and virtue,
was ever intended by divine wisdom to be fully concealed from mankind,
but instead was always held forth,
though sometimes obscurely under types and shadows because of
degenerate minds who were too much prepossessed and darkened to
behold the splendor of the gospel in its clear manifestation.
However, the spiritual and powerful gospel of our Lord was at last
publicly and fully displayed
(apart from ceremonial shadows),
in the dawn of the Christian dispensation at the time of Pentecost, when the disciples,
waiting together in obedience to the command of Christ,
were baptized with His one true permanent baptism--that of the
Holy Spirit--which fulfills and supersedes all other baptisms,
and remains the standing ordinance of God to His church forever.
Then, by revelation, the mystery was conspicuously and powerfully disclosed;
"`which,`" says the apostle,
"`in other ages was not made known unto the sons of men, as,`"--
or in the same degree--"`it is now revealed unto
His holy apostles and prophets by the Spirit;
that the gentiles should be fellow-heirs of the same body,
and partakers of His promise in Christ by the gospel.`"^
footnote:[Ephesians 3:5-6]
"`For now the righteousness of God without the law is manifested,
being witnessed by the law and the prophets.`"^
footnote:[Romans 3:21]

The law witnessed to the gospel:
_First,_ by its various offerings and sacrifices,
pointing out, and keeping in remembrance,
that the Messiah should come in the flesh in order
"`to put away sin by the sacrifice of Himself.`"^
footnote:[Hebrews 9:26]
This was the real purpose of the sin and trespass offerings; for,
"`It is not possible that the blood of bulls and goats should take away sins.`"^
footnote:[Hebrews 10:4]
No, these pointed forward to the precious blood of Christ, both bodily and spiritually;
who, "`by one offering has perfected forever those that are being sanctified`"^
footnote:[Hebrews 10:14]--thereby fulfilling and ending all legal sacrifices.
_Secondly,_ the law witnessed to the gospel by its various sprinklings, washings,
and purifications,
which had no more efficacy towards the removal of sin
and guilt than the blood of bulls and goats.
These were appointed to denote the necessity of real holiness,
and to signify the spiritual administration of Christ,
who gave Himself for us that He might redeem us, not only from guilt and condemnation,
but also from all inward corruption, and to
"`purify for Himself His own special people, zealous of good works.`"^
footnote:[Titus 2:14]
This He does by the "`washing of regeneration, and the renewing of the Holy Spirit.`"^
footnote:[Titus 3:5]

The prophets witnessed to the gospel:
_First,_ by their predictive declarations concerning the coming, sufferings,
and offices of the Messiah; and _second,_
by instructing the people in the necessity of internal, substantial,
effectual religion--preferring it above the written law,
even during the time that the law stood in force.
Samuel said, "`To obey is better than sacrifice.`"^
footnote:[1 Samuel 15:22]
Hosea, "`I desired mercy, and not sacrifice,
and the knowledge of God more than burnt offerings.`"^
footnote:[Hosea 6:6]
David acknowledges to the Lord, "`You do not desire sacrifice, otherwise would I give it;
You delight not in burnt offering.
The sacrifices of God are a broken spirit, a broken and a contrite heart.
These, O God, You will not despise.`"^
footnote:[Ps. 51:16-17]
In his moving address to the Almighty (verse 6) he says,
"`You desire truth in the inward parts;`" and in verse 10 he prays,
"`Create in me a clean heart, and renew a right spirit within me.`"
Micah queries, "`Will the Lord be pleased with thousands of rams,
or with ten thousands of rivers of oil?
Shall I give my first-born for my transgression,
the fruit of my body for the sin of my soul?`"
And then he answers; "`He has showed you, O man, what is good,
and what the Lord requires of you; but to do justly, to love mercy,
and to walk humbly with your God?`"^
footnote:[Micah 6:7-8]
Moses exhorted the children of Israel to "`circumcise the foreskin of their heart;`"^
footnote:[Deuteronomy 10:16]
and told them, "`The Lord your God will circumcise your heart,
and the heart of your seed, to love the Lord your God with all your heart,
and with all your soul.`"^
footnote:[Deuteronomy 30:6]
Here Moses showed them that, though they had received the outward sign of circumcision,
still the reality that God most required was that of the heart, in the Spirit,
which is the inward work of regeneration.
This is the Christian circumcision of which the apostle
speaks--"`He is not a Jew who is one outwardly,
neither is that circumcision which is of the flesh; but he is a Jew who is one inwardly,
and circumcision is that of the heart, in the Spirit and not in the letter.`"^
footnote:[Romans 2:28-29]
He also observes to the Colossians, that in Christ they were circumcised,
"`with the circumcision made without hands,
in putting off the body of the sins of the flesh by the circumcision of Christ.`"^
footnote:[Colossians 2:11]
Thus it is evident that a true knowledge and love of God,
and a change from sin to holiness by the internal circumcision of the Spirit,
was both taught and pressed upon the Jews as the true objective,
without which the observance of the law would avail them very little.
Indeed,
the prophet Isaiah plainly shows that the latter without the former rendered the
practice of the law (though divinely instituted) abominable even to its Institutor.^
footnote:[See Isaiah 1:11-14; 66:3]
