== Chapter 9. The Pure Administration of the Holy Spirit

When the time came wherein the Lord saw fit to call the degenerate
world out from the corruptions in which it had immersed itself,
He raised up the children of Israel as an example to the rest of
mankind by a public manifestation of His own righteous dominion.
He brought them out of their Egyptian bondage by a high hand,
and through many admirable strokes of His power.
He then instituted the Mosaic law, which,
being the introduction of a new form of Theocracy, unknown to the world,
it was necessarily attended by such extraordinary marks of Divine authority
as might sufficiently authenticate and enforce it as coming from the Creator.
He therefore, on that great occasion,
appeared to the Israelites in a manner corresponding to His Almighty sovereignty,
ushering in His covenant with the most dreadful and
astonishing tokens of terror--with thunderings and lightnings,
blackness, darkness, and tempest, the mountain flaming with fire,
the alarming sound of the trumpet waxing louder and louder,
and the voice of words so terrible, that not only the people,
but the whole mountain quaked exceedingly.
This was an obvious and most solemn act of the Supreme Lawgiver of the universe,
and no less authority than His own, could either abolish or alter it.

Therefore, when the period arrived wherein He saw fit to set aside
and supersede His law of outward and carnal ordinances,
by bringing forward into full view and sole obligation
the substance pointed to by it (that is,
His spiritual and more excellent covenant),
it was necessary that it should appear to be done by
clear demonstrations of the same sovereign authority.

Accordingly, the gracious dispensation of the gospel was introduced
by evidences of divine authority equally extraordinary.
Besides the numerous predictions of the prophets concerning the Messiah,
the advent of His forerunner the Baptist,
and the miraculous conception of our Savior by the blessed virgin, etc.,
there were many wonderful works performed by Him and great
signs which accompanied the dawning of the new covenant.
The veil of the temple was rent from top to bottom upon His giving up the Spirit,
denoting the separation, conclusion, and passing away of all signs and ceremonies,
and the unveiling of the substance in Spirit and truth.
Consider also the unaccountable darkness at the time of His death,
His astonishing resurrection,
the bodies of buried saints which arose and went into the city, His visible ascension,
attended with the glorious ministration of angels, etc.
And after all this,
at the time of the Jewish feast of Pentecost (annually observed in
memorial of the giving forth of the law on Mount Sinai),
the Holy Spirit was poured out upon apostles and disciples, male and female,
being assembled together according to the Lord`'s command,
as a demonstration of the commencement of a spiritual covenant,
without any mixture of legal or shadowy figures.
This demonstration was two-fold: _first,_
by the appearance of tongues of fire which sat upon each of them; and _second,_
by filling their hearts with the Holy Spirit to such a
degree that they began to speak with other tongues,
or in other languages besides their own, as the Spirit gave them utterance.
Endued with heavenly wisdom and power, and inflamed with divine love and fervor,
they were now qualified to put in practice the commission before
given (in a verbal manner) by the great Lord and Lawgiver.
To many of them were likewise added the miraculous
powers of healing all manner of diseases.
The dumb were made to speak, the deaf to hear, the lame to walk, the blind to see,
demoniacs were dispossessed, and the dead were raised and restored to life.

Now, these extraordinary powers were neither conferred upon all,
nor confined to the apostles only,
but a measure of the same Spirit was communicated to every one of them,
women as well as men
(according to Peter`'s application of Joel`'s prophecy).
They were all filled with the Holy Spirit, but differently gifted and qualified by it,
for different services, according to the will and wisdom of the great Dispenser.
"`For to one is given the word of wisdom through the Spirit,
to another the word of knowledge through the same Spirit,
to another faith by the same Spirit,
to another gifts of healings by the same Spirit,
to another the working of miracles,
to another prophecy,
to another discerning of spirits,
to another different kinds of tongues,
to another the interpretation of tongues.
But one and the same Spirit works all these things,
distributing to each one individually as He wills.`"^
footnote:[1 Corinthians 12:8-11]
Hence it appears,
that what are commonly called miracles do not
necessarily accompany all divine inspiration,
but are one of several operations of the Spirit which are at times superadded.
These may therefore either totally cease,
when the occasions for which they were added are over,
or continue to be used as it shall appear necessary to Divine wisdom.

When, therefore,
the gospel was so far spread and established in the places then intended,
so that the end for which those extraordinary powers were afforded was answered,
they were largely withdrawn from the church, which was left, in the general,
upon its proper and permanent foundation--the immediate inspiration of the Holy Spirit.
No necessity, therefore,
can be pleaded for the constant continuance of miraculous powers,
or such a spirit of prophecy as signifies the foretelling of future events,
but only of those supernatural influences of the Spirit which are necessary to enlighten,
quicken, regenerate, sanctify, and bring forth the fruits of the Spirit in man.
These are indispensably necessary in every age, being of moral consideration,
and immediately influential in the transformation and salvation of every man.

I believe some divine exertions of a miraculous nature have been evidenced, at times,
under both old and new covenant administrations, as well as before them;
either for the convincement of doubtful persons,
or to give additional weight and authority to
the ministry of some inspired servants of God,
or to encourage and confirm them in their service.
I doubt not but this has sometimes been the case ever since the first century,
and may remain so to the end of time;
for neither the power nor goodness of the Almighty has changed.
Yet I am also of the opinion, that miraculous appearances have been less public,
and more sparingly afforded, since the first century than before it,
which may be in part due to the spiritual declension of the professing churches.
I also believe, according to the prophetic declarations of the apostles,
that under the declined and darkened state of both teachers and hearers,
many strange signs and lying wonders have been, and still may be,
allowed to be imposed upon a gullible and disobedient people by false pretenders,
for the support and spread of their corrupt interests.

Seeing that no further change of dispensations is ever to be made,
nor any other doctrine to be preached but that of our Savior and His apostles (which,
upon its commencement,
received a miraculous confirmation sufficient for its lasting establishment),
people are not now to expect or call for miracles from
those who preach the Christian doctrine.
Instead, all are to turn to, and attend upon that divine Spirit,
pointed out by the Scriptures,
which is manifested in the breast of each
individual--the ministration of Christ in Spirit.
This will give the sincere and humble recipient a more clear and
particular demonstration than all outward signs and tokens could do;
for the powers from which outward miracles proceed may be disputed,
but the internal evidence of the light of Christ, the Life of men,
when rightly waited for and adhered to,
leaves no doubt in the mind concerning its divine nature and authority.

But to return to the ministration of the gospel, the apostle shows (2 Cor. 3)
that it far excels that of the law, and that its excellency stands in its spirituality.
Having spoken of the law in verse 7,
he adds "`How will the ministry of the Spirit not be more glorious?
For if the ministry of condemnation had glory,
the ministry of righteousness exceeds much more in glory.
For even what was made glorious had no glory in this respect,
because of the glory that excels.
For if what is passing away was glorious, what remains is much more glorious.`"
Why is the gospel thus preeminent above the law,
seeing that the law was a divine institution?
Principally, because the gospel is not an outward code as the law was,
but an _inward law of life,_ "`written, not with ink,
but with the Spirit of the living God; not in tablets of stone,
but in fleshy tablets of the heart;`"^
footnote:[2 Corinthians 3:3]
and because it makes "`able ministers, not of the letter, but of the Spirit;
for the letter kills, but the Spirit gives life.`"^
footnote:[2 Corinthians 3:6]

No man can be a true Christian without the Spirit of Christ; for,
"`If any man has not the spirit of Christ, he is none of His.`"^
footnote:[Romans 8:9]
Every Christian ought to experience the indwelling of the Spirit.
"`Know you not that your body is the temple of the Holy Spirit, which is in you,
which you have from God, and you are not your own.`"^
footnote:[1 Corinthians 6:19]
It is requisite to every Christian that he should know
the Spirit to be his guide and leader;
for, only "`as many as are led by the Spirit of God, are the sons of God.`"^
footnote:[Romans 8:14]
No man can be a sheep of Christ without a distinguishing sense of the Spirit of Christ.
"`I am the good shepherd, and I know My sheep,
and am known by My own... My sheep hear my voice, and I know them,
and they follow me... The sheep follow Him, for they know His voice,
and a stranger they will not follow.`"^
footnote:[John 10:14,27,5]
The voice of Christ is the manifestation of His Spirit to the soul.

Without being born again of the Spirit, no man can enter the kingdom of God.
This is as necessary for us now as it ever was to the primitive believers.
Surely it is no more in our ability to regenerate and
prepare ourselves for the kingdom than it was in theirs.
No powers, natural or acquired, in our unregenerate state,
are sufficient for so great a purpose,
nor could they enable us truly to say (with the people of God in former times),
"`Lord, You will establish peace for us; for You have wrought all our works in us.`"^
footnote:[Isaiah 26:12]

Without the Spirit, no man can be a minister of the Spirit.
The apostolic direction is, "`As every man has received the gift,
even so minister the same one to another as good stewards of the manifold grace of God.
If any man speak, let him speak as the oracles of God; if any man minister,
let him do it as of the ability which God gives;
that God in all things may be glorified through Jesus Christ.`"^
footnote:[1 Peter 4:11]
Every true believer and faithful follower of Christ in the apostolic age received a
measure of the same Holy Spirit which the prophets and apostles did,
though in lesser degrees; "`For,`" says Paul,
"`by one Spirit we are all baptized into one body, whether Jews or Gentiles,
bond or free, we have all been made to drink into one Spirit.`"^
footnote:[1 Corinthians 12:13]
Sharing this one Spirit rendered them one body, and joined them to the one living Head.
"`There is one body and one Spirit, even as you are called in one hope of your calling,
one Lord, one faith, one baptism, one God and Father of all, who is above all,
and through all, and in you all.`"^
footnote:[Ephesians 4:4-6]
Thus, according to the several measures allotted them,
they were all partakers of the same Holy Spirit; and as it was then, so it is now,
and ever must be in the true, spiritual church of Jesus Christ.

The gospel sun arose in great splendor,
yet it did not appear to any in its full brightness all at once.
The openings of truth in the minds of the primitive Christians
(apostles as well as others)
were gradual.
As they advanced forward in the new nature, they came to see further and further.
For a time, they occasionally circumcised, entered into vows, anointed with oil,
baptized with John`'s baptism, etc., all of which were of an external and legal nature.
Indeed, at first, they did not even perceive that the Holy Spirit
was to be given to Gentiles as well as to Jews,
though Joel had plainly prophesied it should be poured out upon all flesh.
But afterwards, as they followed Christ in the regeneration,
they were led beyond the first initiatory mixture of things.
In time they came to see clearly how the Holy
Spirit fell upon the Gentiles as well as Jews, and declared that
"`neither circumcision nor uncircumcision avails anything, but a new creation.`"^
footnote:[Galatians 6:15]
They found that "`the anointing from the Holy One`"^
footnote:[1 John 2:20]
is altogether sufficient to give instruction and true judgment;
and they understood that "`the baptism which saves`" is
not that which reaches only to the flesh,
but rather that of the Spirit, which baptizes the heart, and produces
"`the answer of a good conscience towards God, by the resurrection of Christ,`"^
footnote:[1 Peter 3:21]
or by His spiritual arising in the soul.

It is no uncommon thing to hear the apostolic age called the infancy of Christianity;
and as it was in point of time,
so it also was with respect to the temporary
continuation of a few exterior ceremonies and shadows.
These were not immediately seen through,
and afterwards were retained for a season in condescension to those
new believers who had been so much attached to symbolic practices
that they could not quickly be brought to disuse them.
Yet as they grew in the grace and knowledge of Jesus Christ,
the Spirit was at work in them to "`take away the first and establish the second,`"^
footnote:[Hebrews 10:9]
"`removing those things that are being shaken, as of things that are made,
that the things which cannot be shaken may remain.`"^
footnote:[Hebrews 12:27]

In great contrast to this,
many of the present leaders and rulers in churches professing the Christian name,
seem to imagine that,
though the assistance of the Holy Spirit was necessary to the
introduction and support of Christianity in primitive times,
there is no need of it now.
The church, it is believed, has so matured by man`'s wisdom and learning
(which had no share in its origin)
that it is fully capable of going alone.
Thus the church has, in great measure, become another thing,
and stands upon another foundation than formerly.
Though it still calls Christ its head, and accounts itself His body,
it receives no immediate direction from Him, nor feels the circulation of His blood,
which is the life and virtue of all true religion.
So the church today deservedly incurs the
reproof of the apostle implied in this question,
"`Are you so foolish?
Having begun in the Spirit, are you now made perfect by the flesh?`"^
footnote:[Galatians 3:3]
In truth, it too evidently appears that the generality of professed Christian churches,
instead of having advanced to maturity in Christianity,
are in a great decline and apostasy from that state;
otherwise they could not be so insensible,
nor dare appear so opposite to the life of religion as
to reject or belittle the most vital part of it,
treating it as extinct, unnecessary, or at least imperceptible.
Surely a church in this condition is properly entitled to that
address of the Spirit given to the degenerate church of Sardis;
"`I know your works, that you have a name that you are alive, but you are dead.`"^
footnote:[Revelation 3:1]
Nevertheless, though this seems to be too generally the case, I hope, and verily believe,
that there are many living and sensible members
of the body of Christ within those churches.

The vitality and glory of Christianity lies in
the pure administration of the Holy Spirit,
without any veil of legal or ritual shadows.
School learning is but a human accomplishment; and though very useful as a servant,
is no real part of Christianity.
Neither the acquirements of the college, nor the formalities of human authority,
can furnish that humility which fits the heart for God`'s teaching.
Weak humans, possessed of arts and languages,
are puffed up with a conceit of superiority which leads
away from self-denial and the daily cross,
into pride and self-sufficiency.
These, instead of waiting for and depending upon the wisdom and power of God,
grow into a confidence in the wisdom of this world,
and a satisfaction with the repetition of external forms and ordinances.
On the other hand, those that
"`worship God in Spirit, rejoice in Christ Jesus,`"
put "`no confidence in the flesh.`"^
footnote:[Philippians 3:3]
And why?
Because "`it is the Spirit that gives life; the flesh profits nothing.`"^
footnote:[John 6:63]
Therefore, whosoever denies that the Holy Spirit and its internal
operations are now to be sensibly experienced,
only demonstrates their own insensibility of it.
The true people of God in all ages have declared their own
undoubted sense of divine illumination and empowering;
and the apostles testify unanimously that they had a clear,
distinguishing sense of the Holy Spirit in its manifold operations.
As it was then, so it is now, and must remain as long as men are upon earth.

The same inward work of God is absolutely necessary in every man,
and a corresponding sense of it (in measure) is clear
and certain to all who experience regeneration.
Just as sure as no man can obtain true happiness outside of God`'s kingdom,
nor enter the kingdom without being born of the Spirit,
neither is the work of the new birth wrought imperceptibly in any soul.
Whatever secret or unknown means men might imagine or allege,
an insensible operation of the Holy Spirit is not regeneration; it is mere deception.
The Spirit of God, whether it operate by words and instruments, or without them,
always comes in power--a power which gives an
undeniable sense which is perfectly distinct from,
and above, all other powers, and which manifests a brightness that, at times,
far exceeds all natural lights,
even as the radiant sun exceeds the faint glimmer of a glow-worm.
This Holy Spirit of divine light and power of life, is the great,
fundamental principle of the reproached Quakers,
and the only true saving principle for all mankind.
It is Christ in Spirit,
"`a light to enlighten the Gentiles, and God`'s salvation to the ends of the earth;`"^
footnote:[Isaiah 49:6]
who always became, and stands always ready to become,
the "`author of eternal salvation to all them that obey Him.`"^
footnote:[Hebrews 5:9]
