== Chapter 10. The Operation of Divine Grace

Having endeavored plainly to show forth something of the fall of man,
and the necessity and means of his restoration to God,
I shall now proceed to take particular notice of
some common errors and misunderstandings,
beginning with the notions of individual
predestination and the operation of divine grace.

Though man cannot take a single step towards his salvation
without the assistance of the grace of God as the first and
continual enabling cause (both of the will and the deed),
it does not necessarily follow (as some reformers have insisted) that
God is therefore the author of salvation to some,
and the author of destruction to others.
The truth of this matter, as clearly laid forth in Scripture, is as follows:
_1+++.+++_ That man has no ability to save himself,
nor is he naturally in a state of equal freedom to do good or evil at his pleasure,
nor is he in possession of that faith which is necessary to his salvation.
_2+++.+++_ That the Redeemer affords a manifestation of His Spirit to the soul of every man,
by which, at seasons, He checks man`'s corrupt inclinations, stops them in their tracks,
and puts it in man`'s power to reflect upon his present condition,
and yield to the operation of this inward Spirit.
If he does not resist, but rather stands in submission,
the Spirit then takes further hold of him, giving him ability to believe, to unite with,
and to abide in the Spirit`'s operation upon him.
In this situation,
he feels strength and comfort spring up from the Seed
(or measure of grace)
which increases his faith and trust therein,
and gradually enables and engages him to become active--that is,
to join heartily in concurrence with its operations, and to proceed from faith to faith,
and from one degree of grace to another.
This progresses until the soul comes to know and
experience a veritable new birth of the Spirit,
participating (in measure) in the glorious light, life,
and nature of the heavenly kingdom.

God has made man a reasonable creature,
and therefore requires a willing obedience of him--
"`If you are willing and obedient, you shall eat the good of the land.`"^
footnote:[Isaiah 1:19]
Can we think that He places good and evil,
life and death before men (as the sacred records testify),
and calls them repeatedly to choose life and good, and yet does not enable them so to do?
Indeed, every divine precept, every exhortation, every command, every warning,
implies a liberty afforded to comply or refuse; to obey, or disobey.
However, if God repeatedly visits all with the reaches of His grace,
and continues time after time to convict, persuade,
and woo (as the Scriptures declare) that He may prevail upon man to come to repentance,
does He not go as far as possible without violating the rational liberty He affords?
Let man but yield obedience to His convictions,
and then see if he can charge his Creator with partiality, or with hard usage.
It is the unprofitable and lazy servant that makes such charges against his Master.

Education and tradition do certainly prepossess individuals,
and give a bias to the mind against every
doctrine different from those it has been taught.
Nevertheless, the divine light, at times, darts in upon the soul unaware,
as quick as lightning, and penetrates through all darkness and every false color,
disturbing it in its polluted rests and carnal gratifications,
showing its bondage under them, and inspiring a secret wish and sigh to be delivered.
This, being an opening of divine light upon the mind,
is called __the day of God`'s visitation,__^
footnote:[Luke 19:44; 1 Peter 2:12]
the time of grace unto man, wherein life and death are distinguished in him.
At this time,
man is not only given liberty to choose life (which he could not do before),
but he is also given a corresponding measure of ability
to love and cleave to the grace that visits him,
and thereby to come to repentance and salvation.
For this grace is the Spirit of the Savior, and so brings the power of salvation with it,
as the apostle says,
"`For the grace of God that brings salvation has appeared to all men, teaching us that,
denying ungodliness and worldly lusts, we should live soberly, righteously,
and godly in the present age,
looking for the blessed hope and glorious appearing of
our great God and Savior Jesus Christ.`"^
footnote:[Titus 2:11-13]

These merciful visitations of divine grace are often repeated, by night as well as by day.
"`God,`" says inspired Elihu, "`speaks once, yes twice, yet man perceives it not.
In a dream, in a vision of the night, when deep sleep falls upon man,
while slumbering upon their bed.
Then He opens the ears of men, and seals their instruction,
that He may withdraw man from his purpose, and hide pride from man.`"^
footnote:[Job 33:14-16]
He then proceeds to show how the Lord operates upon the
submissive soul in the work of repentance and mortification,
and what the result shall be.
Afterwards, he summarizes with these words, "`He looks upon men, and if any say,
'`I have sinned, and perverted what was right,
and it profited me not,`' He will redeem his soul from going into the pit,
and his life shall see the light.
Lo, God works all these things oftentimes with man, to bring his soul back from the pit,
to be enlightened with the light of life.`"^
footnote:[Job 33:27-30]

Indeed,
the great Father of mercies is pleased to continue his
gracious visitations from on high to backsliding men,
until they have become so determined in wickedness,
and so habitually united to its servitude, that like the servants in Exodus 21:5-6,
they will not be freed from it.
Then night comes upon them, and the day of their visitation ceases;
for God will not always strive with those who have been long and often reproved,
and yet still stiffen their necks.
No, after long forbearance, He withdraws the reaches of His merciful loving-kindness,
and allows them to incur that dreadful sentence, "`He that is unjust,
let him be unjust still; and he that is filthy, let him be filthy still.`"^
footnote:[Revelation 22:11]

When persons are thus judicially hardened,
and given up to their own hearts`' lusts and beloved delusions,
and are left in a state of insensibility to the divine Spirit,
they may blindly mistake their condition for one of peace and security.
To such as these,
the conscience becomes obscured--like a book shut up which they cannot read.
But in the day of the righteous retribution of the great Judge of the living and dead,
this hidden volume will again be unfolded by Him who opens and none can shut,
and a righteous distribution will be made to
everyone according to what is written therein.
This will prove either a book of life or a book of death to every man--"`eternal
life to those who by patient continuance in doing good seek for glory,
honor, and immortality; but to those who are self-seeking and do not obey the truth,
but obey unrighteousness--indignation and wrath.`"^
footnote:[Romans 2:7-8]

We therefore rationally conclude,
that God does not only set good and evil before man in their right distinctions,
but at the same time, enables him to choose which he will follow.
Furthermore, God stirs up and assists man to desire after true happiness,
and as the heart abides in this desire, He empowers man to strive, press,
and wrestle effectually for deliverance and preservation.

The inmost motions of the human will are impossible to
discern without the light of God`'s Spirit,
and from lack of discernment,
some have taken occasion to charge God as the one responsible for the
various responses of mankind to the visitations of divine grace,
rendering Him the primary author of man`'s evil, rebellion, and damnation.
But is it not absurd to suppose that God would
voluntarily produce what is contrary to His nature?
Is not all sin a transgression of God`'s will, and all vice contrary to His nature?
How then could these be produced by an act of His will,
or be the genuine fruit of His power, either mediately or immediately?
Can a right understanding lead any man to think that the will of God is, at any time,
contrary to His nature?
From purity, goodness, and virtue, no impurity, vice, or evil could naturally arise.

But some Scriptures have been objected, such as,
"`It is impossible but that offenses will come.`"
True; but from where do they come?
Not from God, but from that root of corruption which has entered and overspread the world.
While this corrupt root remains, offenses will naturally spring up from it;
and the same text pronounces, "`Woe unto him through whom they come.`"^
footnote:[Luke 17:1]
But the Lord says "`I create evil;`"^
footnote:[Isaiah 45:7]
and the prophet says, "`Shall there be evil in a city, and the Lord has not done it?`"^
footnote:[Amos 3:6]
Moral evil is not intended here,
but rather the natural evil and calamity of pain and distress, through hostility,
sickness, famine, etc.,
which are the judgments of God upon men for
disobedience and for the commission of moral evil.

Therefore, according to my apprehension,
sin consists in the creature`'s preferring the indulgence of
its depraved nature over the obedience of divine grace;
which indulgence leads to the abuse of that grace, and so to think, speak,
and act against the manifest will of its Creator.
Now, that some obey, and others refuse obedience to the manifestations of divine grace,
is certainly true; but we believe the cause of this difference is not of God,
but entirely owing to the individual.
Indeed, there is no difficulty in supposing that the same nature should have
different effects in subjects who are in different conditions.
For it is evident to every man`'s observation,
that the beams of the sun will both soften tar and harden clay.
These contrary effects arise not from a difference in the sun`'s rays,
but from a difference in the disposition of tar and clay to receive them.
In a like manner, I apprehend,
the Holy Spirit operates differently on different persons by reason
of their different states and dispositions to receive His influences.
Let him that doubts this inquire in his own conscience,
and the faithful witness there
(by its condemnations for evil)
will plainly show that the fault is his own.
What man is there upon earth who has not been struck with guilt and remorse?
Or who has not felt at times inclinations and dispositions
excited in him towards virtue and a good life?
And having followed this guide, has he not found peace in his obedience?
But having turned from it to pursue something of a contrary nature,
has he not incurred trouble and condemnation?
Can a reasonable creature need further proofs that both
the convicting reproofs and comforts are the internal,
immediate judgments of a just, good, powerful, omnipresent, omniscient Spirit?
And for what end does God thus attend every soul of man,
but that all may come to repentance and experience salvation?

So then, the first moving, true,
and proper cause of man`'s salvation is the goodness and love of God to him,
and the essential means by which He effects salvation,
is the operation of His own Holy Spirit on the soul of man, often directly,
and sometimes making use of a secondary means, such as preaching,
reading the Scriptures and other good books, pious conversation, worship, mercies,
distresses, etc.
But it is God, by His own Holy Spirit, who works all good in man,
both as to the will and the deed.
It is by grace we are saved, through faith, or in the way of faith.
This faith works by the love of God^
footnote:[Galatians 5:6]
to the purifying of the heart,^
footnote:[Acts 15:9]
and the production of good works.^
footnote:[James 2:14-26]
These works are the genuine fruits of true faith, and inseparable from it:
therefore without works we cannot be saved.^
footnote:[James 2:24]
Yet it is not _by_ the works that we are saved, as the cause of salvation to us,
but by grace (which is their root), and the faith, by which we believe in God,
open to and receive Him, cleave to Him, trust in Him, and so lay hold of eternal life.

This faith is not our faculty, but rather the gift of God to us.^
footnote:[Hebrews 12:1-2, Peter 1:1, Philippians 1:29]
It comes by grace, the free grace of God, who is
"`not willing that any should perish, but that all should come to repentance.`"^
footnote:[2 Peter 3:9]
He whose works are evil, has not this saving faith,
regardless what doctrines or notions he believes.
For where true faith is, it necessarily produces good works.
Indeed, this root is never without its fruits.
"`Show me your faith without your works, and I will show you my faith by my works,`"^
footnote:[James 2:18]
says the apostle James.
Nevertheless, these works do not _merit_ salvation,
for they are not to be attributed to us, but wholly to Him who, through His grace,
has brought us into the blessed state of living faith wherein they are produced.
"`For by grace you have been saved through faith, and that not of yourselves;
it is the gift of God, not of works, lest anyone should boast.
For we are His workmanship, created in Christ Jesus for good works,
which God prepared beforehand that we should walk in them.`"^
footnote:[Ephesians 2:8-10]

All the souls that God has made are equally His,
and He whose mercies are over all His works,
overlooks none of His creatures in the distribution of His mercies.
He withholds His talents from none,
but dispenses them in different portions to different persons.
To one He gives five talents; to a second, two; to a third, one;
but to each is given a divine manifestation sufficient to operate to his salvation,
if believed in and obeyed.
The Creator justly requires an increase corresponding to the measure He affords;
and as He perfectly knows to what degree of improvement each might have attained,
He will finally judge all according to their increase, their negligence,
or their total rejection of the talent received.

Through a misapprehension of the second commandment, the people of Israel,
in Ezekiel`'s time,
had espoused a notion that the children were punished for the sins of their parents,
so that it had become a proverb among them,
"`The fathers have eaten sour grapes, and the children`'s teeth are set on edge.`"
The prophet, therefore,
was particularly commissioned to declare God`'s immutable will in opposition to this:
"`'`As I live,`' says the Lord God, '`you shall no longer use this proverb in Israel.
Behold, all souls are Mine; the soul of the father as well as the soul of the son is Mine.
The soul who sins shall die.`"^
footnote:[Ezekiel 18:3-4]
"`The son shall not bear the iniquity of the father,
neither shall the father bear the iniquity of the son;
the righteousness of the righteous shall be upon himself,
and the wickedness of the wicked shall be upon himself.`"^
footnote:[Ezekiel 18:20]
"`Yet you say, '`The way of the Lord is not fair.`'
Hear now, O house of Israel,
is it not My way which is fair, and your ways which are not fair?
When a righteous man turns away from his righteousness, commits iniquity, and dies in it,
it is because of the iniquity which he has done that he dies.
Again, when a wicked man turns away from the wickedness which he committed,
and does what is lawful and right, he preserves himself alive.
Because he considers and turns away from all the transgressions which he committed,
he shall surely live; he shall not die.`"^
footnote:[Ezekiel 18:25-28]
"`Therefore, I will judge you, house of Israel, everyone according to his ways,
says the Lord God.
Repent, and turn yourselves from all your transgressions;
so that iniquity shall not be your ruin.`"^
footnote:[Ezekiel 18:30]
The prophet repeats more to the same purpose, both in this chapter,
and in the 33rd. "`'`As I live,`' says the Lord God,
'`I have no pleasure in the death of the wicked,
but that the wicked turn from his way and live.
Turn, turn from your evil ways!
For why should you die, O house of Israel?`'`"^
footnote:[Ezekiel 33:11]
"`Yet the children of your people say,
'`The way of the Lord is not fair.`'
But it is their way which is not fair!
When the righteous turns from his righteousness and commits iniquity,
he shall die because of it.
But when the wicked turns from his wickedness and does what is lawful and right,
he shall live because of it.`"^
footnote:[Ezekiel 33:17-19]
Now, it is manifest that the death spoken of in these
Scriptures is not the common death of the body;
for in that respect, the same event happens to the righteous and the wicked.
Surely the death mentioned here refers to the everlasting and unhappy state of
souls who go out of time into eternity without repentance and regeneration.

From all these express declarations,
it is evident that the Almighty "`does not afflict willingly,
nor grieve the children of men;`"^
footnote:[Lamentations 3:3]
and that He is "`not willing that any should perish,
but that all should come to repentance,`"^
footnote:[2 Peter 3:9]
desiring "`all men to be saved and to come to the knowledge of the truth.`"^
footnote:[1 Timothy 2:4]
These are all plain manifestations of the mind of God on this point,
and ought to be decisive.
The sins of men are placed to the account of their own will, and not to the will of God.
"`For why should you die, O house of Israel?`"^
footnote:[Ezekiel 18:31, 33:11]
And indeed, it is clear He does all that can be done by fair means to prevent it.
By that pressing repetition,
"`Turn you, turn you from your evil ways,`"
it is manifest how He puts it in the power of men to turn from them.
Who then can justify their perverseness, or in any way charge their sin,
either immediately or remotely, to His account?
Men are not destroyed through any malevolence in their Creator,
but instead are saved by His grace,
which He dispenses to all from that unparalleled benevolence
which arises purely from His infinite goodness.
Sinful man has nothing to offer.
God, therefore, will have mercy because He will have mercy.
Yes, because He is full of mercy,
He will dispense it to His helpless and unworthy creatures.
"`I,`" says the Lord to the repenting sinner,
"`even I am He that blots out your transgressions for My own sake,
and I will not remember your sins.`"^
footnote:[Isaiah 43:25]

Various texts and portions of Scripture have been pressed and used to
ascribe a cruel partiality to our Creator and Benefactor.
We are told that He ordered the obstinacy of Pharaoh, the sin and folly of Sihon,
and the kings of Canaan,
the treacherous rebellion of Zedekiah against the king of Babylon,
the ravages of Nebuchadnezzar, etc.
But properly considered, this was an ordering of punishment for sin,
and not an ordering of sin for punishment.
The Lord hardens none till they have hardened
themselves past all probability of repentance,
and then He leaves them to the disorder of their own beloved lusts and vices.
And what are considered to be unrighteous ravages,
though really such in the committers of them, are, respecting the Almighty,
the righteous execution of His justice against those
who have filled up their measure of iniquity,
and abused His gracious goodness and long forbearance towards
them until He sees fit no longer to continue it to them.
Thus He punishes the settled wickedness of some by the wickedness of their enemies,
which He permits to be turned upon them.
But afterwards He proceeds in like manner with
those who were His instruments of chastisement,
when they also have filled up their measure.

The divine Being is but one essence, perfectly pure and simple.
He is one eternal, immutable power, making and supporting all other beings,
and operating variously according to the state of His subjects,
but never contrarily towards subjects in the same condition.
As all souls are equally His immediate creation, no just reason can be advanced why He,
who is righteous in all His ways, and holy or merciful in all His works,
should deal so unequally with them as to predetermine some to eternal happiness,
and others to inevitable misery.
Oh, His mercies are over all, and to all, with a just and gracious intent towards all!
The gracious Redeemer purchased gifts of grace for those who prove rebellious,
as well as for others,
and all are visited with a manifestation of His Spirit that they may profit by it.
And though men do lapse from the visiting power,
and often turn from the assistance afforded them, still He follows them, time after time,
in long forbearance, and often revisits them of His freely abounding grace and mercy,
that they may be prevailed upon to come to repentance and be saved.
The condemnation of men, according to our Savior,
is not the fruit of any previous decree, for "`This is the condemnation,
that light is come into the world, but men loved darkness rather than light,
because their deeds were evil.`"^
footnote:[John 3:19]
