== Chapter 11. The Scriptures and the Spirit

With respect to the Scriptures,
we are so far from lessening them or opposing the true sense of them,
that we verily believe, and sincerely assert, that the Holy Spirit,
in whatever degree of illumination it appears, can never contradict them.
It is the private or particular interpretations of man, without divine illumination,
that we object to, as being insufficient to give the true meaning of disputed Scriptures.
Besides man`'s natural inability, his various prejudices, prevailing passions,
different interests, and diverse leaders, all contribute to give different,
and sometimes opposite interpretations of the sacred text.
Many have the words of the Spirit in Scripture,
who have not the mind of the Spirit in their hearts.

Without divine illumination,
man does not have sufficient ability to ascertain the
genuine sense of doubtful and disputed texts,
which are very numerous.
Indeed, the great diversity in interpretation by persons of apparently equal sincerity,
and of the best natural and acquired abilities, under the same,
as well as different denominations,
plainly indicates how the assistance of the divine Author
Himself is imperative for the right understanding of them.
I have previously shown how man`'s reason is too much clouded and biased by
his passions and prepossessions to be justly called _right_ reason,
for it often manifests a great diversity concerning spiritual matters,
and even an instability in the same person.
Right reason is truth, unchangeably the same and incapable of error,
and therefore exists only in the divine nature, which man must, in measure,
become a partaker of, in order to rectify his fallen and fallible reason.

Neither nature nor education can give a man the sense of the Holy Spirit,
nor interpret the Spirit`'s expressions with certainty.
It is therefore truly asserted, not only by the Quakers,
but also by an abundance of distinguished writers of various professions,
ancient and modern,
that the internal illumination of God`'s Holy
Spirit is absolutely necessary to every man,
in order to rightly understand the Scriptures.

Now, many press their own particular opinion of parts of
Scripture as the true intention of the Holy Spirit,
though they deny a sense of the Holy Spirit`'s illumination in their hearts.
But why should any credit be given to their assertions,
seeing there is such a diversity of other opinions?
They allege, '`the Scripture is infallible!`' I grant it;
but how is its true meaning to be infallibly conveyed to every reader?
By human study and instruction?
That has led into all the differences and disagreements about it!
The plain truth of the matter is that nothing but the Spirit of divine Wisdom,
from which the Scripture came, can give the genuine sense of it.
For, "`No one knows the things of God except the Spirit of God.`"^
footnote:[1 Corinthians 2:11]
What is the infallibility of Scripture to one who knows not the infallible Teacher of it?
If all who had the Scriptures knew this Teacher, none could misunderstand,
or differ with each other about them.
Yet it is too manifest, by the differences among Christians,
that they _do_ misunderstand them.
Such confusion is not to be imputed to any defect in the sacred writings,
but to the common unfitness of men`'s understandings to
discover the right sense of God`'s words.
What then is able to open the Scriptures to man`'s capacity besides the Holy Spirit?
The question is not whether the Scriptures,
as written by divine inspiration, are infallibly correct.
No doubt they are.
The question is whether everyone that reads them is infallibly able to understand them?
Some suggest that, if the Scriptures cannot be understood without the Spirit,
they are given in vain.
But this is to contradict the Scriptures themselves,
which plainly declare that
"`the manifestation of the Spirit is given to every man to profit withal.`"^
footnote:[1 Corinthians 12:7]
The words of the apostle are clear in this regard: "`Now we have received,
not the spirit of the world, but the Spirit who is from God,
that we might know the things that have been freely given to us by God.
These things we also speak,
not in words which man`'s wisdom teaches but which the Holy Spirit teaches,
comparing spiritual things with spiritual.
But the natural man does not receive the things of the Spirit of God,
for they are foolishness to him; nor can he know them,
because they are spiritually discerned.`"^
footnote:[1 Corinthians 2:12-14]

Scripture doctrines are of various kinds.
They exhibit just morals and benevolent conduct in a manner
superior to the best ethical writers in all ages and nations.
These are generally and justly accepted to be of natural, universal,
and unalterable obligation,
and are sufficiently plain and clear to the common understanding of every man.
But matters relating to faith and worship,
having gone through many circumstantial additions and alterations,
according to the different dispensations of divine Wisdom,
have not been so clear to men`'s understandings,
nor have men been so united in judgment concerning them as in the case of moral duties.
Ever since the collected publication of the New Testament,
differences in opinion about true meaning, especially in matters of faith,
have subsisted and abounded; and what can determine these differences?
The learned scholar A. says a particular text means such and such.
The learned scholar B. insists it is to be understood in a different,
perhaps contrary sense.
They appeal to the context and yet remain equally different in opinion,
and certain of being in the right.
They move from text to text, and from critic to commentator,
till they have exhausted everyone they can find or force to their purpose,
and still remain equally, if not more in discord than at the beginning.
What is left them to determine the matter?
Will churches or councils do it?
They jangle from year to year, or from age to age,
and leave the difference as wide as they found it.
The true sense still remains only with the divine Author of the disputed texts,
and He alone is able to communicate it.
Alas, this case has subsisted for a great many centuries,
and must always continue while men prefer their own prejudices, imaginations,
and reasonings, to the internal leadings of the Spirit of Truth.

We hold the Scriptures to be the governing and guiding rule to all that have them,
so far as they have a right understanding of them;
but we cannot affirm they are the sole, the primary,
and the universal director of mankind in matters
of religious duty for the following reasons:
1+++.+++ They are not the _sole_ director because the Spirit of God in
the heart and conscience of man is also an undeniable director.
2+++.+++ They are not the _primary_ director,
because the illumination of the Holy Spirit that gave them forth is
necessary to open the true sense of many parts of them,
about which the apprehensions of men so much differ.
The Spirit from which the Scriptures came, being their origin,
is therefore primary to them;
and since the Spirit alone can unveil the meaning of His words,
the words are therefore secondary to the Spirit, as an instrument in His hand.
3+++.+++ They are not the _universal_ director, because it is not probable that one in ten,
if one in twenty, of mankind, have ever had the opportunity of possessing them.
Seeing therefore this is the case, they cannot properly be pronounced the complete,
adequate, universal rule of mankind.

We therefore esteem the Scriptures the secondary rule or guide of Christians,
which have been divinely communicated for the use of all to whom they may come.
And since they are intrinsically superior in excellence to all other writings,
we prefer them above all others,
and we as gratefully and comfortably use them as any Christians upon earth,
verily believing that they "`were written for our learning, that we,
through patience and comfort of the Scriptures, might have hope.`"^
footnote:[Romans 15:4]
We do not depreciate the Scriptures, but indeed hold them in their proper place,
as superior to all works of men,
but subordinate to their Supreme Communicator and only sure Expounder.
For the Holy Spirit is necessary for the right use of them,
as an agent with an instrument;
and what is an instrument without a hand to guide and enforce it?
And which is superior, the agent or the instrument?
The Holy Spirit is the original wisdom from which the Scriptures came,
and the sole power that can open them and give their right effect.
The Spirit of Truth is given to guide into all truth,
and is the only thing that can do it,
being consequently the Supreme Guide afforded to mankind.

It is both unwarrantable and irrational to assert that anything could act as the sole,
or primary director, when the Spirit of God is communicated for that purpose.
The same passages of Scripture appear as differently to each
person as their understanding differs one from another.
Human understanding, therefore, must be rectified,
to enable them to see those truths in the same light.
The Rectifier is the Spirit of Truth, who alone can unite men in a true sense.
We hesitate not to call the Scriptures collectively a divine rule;
but we object to calling them _the_ rule of faith and practice,
lest this should imply we look for nothing further to be our guide or leader.
The Scriptures themselves abundantly testify that there is something superior to them,
which all ought to look for and attend unto.
That something is the Holy Spirit of the Supreme Legislator of men,
the Spirit of the Author of the sacred writings.
And it is in and by His light and power that the Scriptures are made
instrumentally useful and adequate to the purposes intended by them.
Like a good sundial, they are true and perfect according to their purpose and kind,
that is, as writings.
However, they may justly bear the same motto with the sundial--__Non sine lunine__
(that is, '`Nothing without light`').
For as a sundial without
the rays of the sunbeams has no proper use,
neither does an ambiguous passage of Scripture infallibly communicate
the mind of the Holy Spirit to different understandings,
except the luminous beams of the Sun of Righteousness uncover it to the attentive mind.

Our opposers call the Scriptures the _primary_ rule.
We confess it is the primary _written_ rule, and in all disputes between them and us,
we abide by its decision, according to our understanding of the meaning of it,
which they profess to do likewise by theirs.
In all public differences therefore we refer intentionally to the same rule with them.
But we also have both plain Scripture and experience to support our belief that,
with respect to the particular duty of individuals,
everyone has in his own breast a nearer and more
certain rule or guide of conscience than the Scriptures,
namely--"`the manifestation of the Spirit given to every man to profit withal.`"^
footnote:[1 Corinthians 12:7]
And when this guide is duly observed,
it gives both a right interpretation of Scripture (so far as is necessary),
as well as a sense of each particular person`'s duty.
Indeed,
when a person feels the faithful witness of God in his
conscience condemning him for what is wrong,
and approving him for what is right, does he not find it to speak more clearly,
particularly,
and convincingly to his case and state than what he can read in the words of Scripture?
And will he then conclude that this truly discerning
witness is less than that Spirit of Truth,
or Comforter, which "`convinces the world of sin, of righteousness, and of judgment?`"^
footnote:[John 16:8]
But alas, in those who regard not this heavenly witness,
I have observed that every man`'s opinion of Scripture _is_ his Scripture,
and when he proposes his opponent shall be determined by Scripture,
he means according to his own apprehension of its meaning.

When Christ, after His resurrection,
"`opened the understandings of his disciples that they might understand the Scriptures,`"^
footnote:[Luke 24:45]
was not the divine illumination in their understandings a more clear, certain,
and superior evidence of their meaning,
than all their reading and study could have afforded them without such illumination?
Has mankind become so much more wise and perceptive that they now
have no need of His assistance to open their understandings?
Is their school and college learning so perfect
as to render God`'s illumination quite needless?
Are the innumerable clashings and janglings of the book-learned priests and
teachers about the meaning of Scripture a proof of the unity of their sentiments?
Oh consider, how can they claim Scripture as the final and certain criterion,
when it is precisely the meaning of Scripture which
gives rise to all uncertainty and difference?
It is therefore certain that, without divine illumination,
every reader of sacred text accepts whatever meaning his presuppositions make for him,
which is the cause of the innumerable differences amongst professing Christians.
