== Chapter 12. The Purifying Power of the Gospel

I judge this a proper opportunity to caution against the
corrupt and dangerous positions that some have publicly avowed
respecting true righteousness and sanctification.
Many have plainly taught or implied:

[.numbered-group]
====

[.numbered]
1+++.+++ That man, at the same time he is actually unrighteous in himself,
is righteous in Christ.
That is, he is not what he is in reality, but what he persuades himself to be,
by a false imagination concerning the sacrifice of Christ.
These are like "`that generation who are pure in their own eyes,
yet are not washed from their filthiness.`"^
footnote:[Proverbs 30:12]

[.numbered]
2+++.+++ That the supreme Being of immutable truth looks upon man in a false light,
esteeming him pure, while he knows him to be sinful and corrupt.

[.numbered]
3+++.+++ That Christ, the Truth, is something of a false medium,
showing the states of men contrary to what they are in reality.

[.numbered]
4+++.+++ That man can be the servant of Christ while he is under the influence of antichrist;
that he is holy by imputation, even while he is ruled by the author of pollution,
the adversary of all holiness;
and that he is acting in the will of God while he is doing the works of the devil.

====

Much to the contrary we read,
"`Do you not know that to whom you present yourselves slaves to obey,
you are that one`'s slaves whom you obey, whether of sin leading to death,
or of obedience leading to righteousness?`"^
footnote:[Romans 6:16]

It is a vain delusion for any to expect that purity in the highest perfection
should unite with them while they remain in the very cause of separation from Him.
Sin made the separation at first, and the continuance of it maintains the separation.
If it be asked--Did not Christ die to reconcile sinners to God?
I answer: Yes; but not to reconcile God to sin, nor to save sin.
He suffered not to purchase a license for sinners to continue as such,
but to open the way for them to come to repentance,
through the gift of grace procured by Him.
"`For,`" says he, "`Except you repent, you shall all likewise perish.`"^
footnote:[Luke 13:3,5]
He came not to uphold, but "`to destroy the works of the devil,`"^
footnote:[1 John 3:8]
which include all manner of sin and corruption.
"`Do you not know`" says the man of God,
"`that the unrighteous will not inherit the kingdom of God?
Do not be deceived.
Neither fornicators, nor idolaters, nor adulterers, nor homosexuals, nor sodomites,
nor thieves, nor covetous, nor drunkards, nor revilers,
nor extortioners will inherit the kingdom of God.`"^
footnote:[1 Corinthians 6:9-10]
The notion of imputed righteousness to such as remain in the
commission of these evils is therefore a vain and pernicious error.
We must die to sin, or we cannot live to God; and in proportion as we die to sin,
we live in Christ, and no further.
We must put on Christ, by true faith and obedience,
which are never separate--for it is a false faith which abides in disobedience.
"`Faith without works is dead,`"^
footnote:[James 2:26]
says the servant of Christ; and "`Show me your faith without works,
and I will show you my faith by my works.`"^
footnote:[James 2:18]

The gospel not only forbids the outward acts of sin,
but also subdues the inward desire and motion towards it.
The law says, '`Thou shalt not kill; nor commit adultery; nor swear falsely,
etc.`' The gospel commands, '`Give no place to anger; you shall not lust;
swear not at all, etc.`' In this manner the gospel does not destroy the moral law,
but rather fulfills it, taking away the seat of sin,
and laying the axe of the Spirit to the root of corruption.
Can a reasonable man imagine that the everlasting Source of wisdom and might is at
a loss how to expel Satan`'s kingdom in man while he lives upon the earth?
Or do they think God is pleased with man`'s offenses against His purity and goodness,
and willing that Satan should reign over His creatures to the last moment of their lives?
Would it not be more to God`'s glory to deliver from the present reign of sin,
saving from evil and misery both here and hereafter,
rather than only to save from future wretchedness?
Is an incomplete deliverance preferable or more glorious than that which is perfect?
When doctrines contrary to purification of heart and holiness
of life are actively propagated amongst professing Christians,
it behooves all to be alarmed and fearful, lest by giving them place in their minds,
they become blinded through the deceitfulness of sin.
Indeed, this will land them at last in a fool`'s paradise, instead of in the city of God,
the heavenly Jerusalem, into which
"`nothing that defiles, that works abomination, or makes a lie, shall by any means enter.`"^
footnote:[Revelation 21:27]

The apostle Peter spoke of a faith that "`purifies the heart,`"^
footnote:[Acts 15:9]
and what this true gospel faith is, we would do well to consider.
As the entrance of the divine Word quickens the soul,
so it first communicates a degree of faith by which it operates.
For all true faith is the gift of God, and the Holy Spirit is the Spirit of faith,
which is not a bare belief in the truths concerning Christ, but a faith in Him.
Faith in Christ does not consist in giving
credit or acceptance to narrations and doctrines,
together with modes of practice framed by the wisdom of men.
Truly, all this falls far short of the essential substance of faith.
Gospel faith operating in man believes the truth of all that is revealed by the Spirit,
both in the heart and in the Sacred Writings, because it feels the truth, savors it,
and is one with it.
It not only assents to the Scriptural accounts of the
incarnation and whole process of Christ in Judea,
but it also receives His internal appearance, consents to His inward operation,
and concurs with it.
That faith which stands wholly upon hearsay, tradition, reading, or imagination,
is but a distant kind of ineffectual credence,
which permits the soul to remain in the bondage of corruption.
The wicked may go this far towards gospel faith,
but true faith lays hold of and cleaves to the
Spirit of Truth in its inward manifestations,
wherein it stands, and whereby it grows, till the heart is purified, the world overcome,
and salvation obtained.

Gospel faith is as a flame of pure love in the heart to God.
It presses towards Him, pants after Him, resigns to Him, confides and lives in Him.
"`The mystery of faith is held in a pure conscience,`"^
footnote:[1 Timothy 3:9]
and in the effective power of the everlasting gospel.
By this faith the Christian dispensation is often distinguished in
Scripture from the exterior dispensation of the Mosaic law.
Though the term faith is occasionally used by the penmen of
Scripture in diverse (yet not contrary) senses,
this seems to be the one standing faith mentioned in Ephesians 4:5,
which faith is in Christ Jesus,
and is the fruit of His grace and good Spirit in the heart.
Through this alone the Scriptures become effectually instructive to the man of God,
and helpful to the Christian in the way of life and salvation.
This is the faith by which the members of Christ truly live and abide as such.
Yes, faith is their invincible shield,
and the knowledge of Christ in them is the proof of their possessing it.

Abundance could be said of the nature, power, and effects of this all-conquering faith,
but I hope this will be sufficient to show that it arises not in man merely from the man.
Though in its complete sense it includes a belief of all that is said about Christ,
and by Christ, in Holy Writ; still it goes much deeper, taking its birth,
and receiving its increase from the operation of the Holy Spirit,
which works by it towards the sanctification of the
heart and the production of every Christian virtue.

It is by continuing in this faith that man lays hold of the hope of the
gospel--a gospel that is _described_ by the evangelical and apostolic writings,
but _defined and experienced_ as the "`power of God unto salvation.`"^
footnote:[Romans 1:16]
Indeed, Christ Himself is called "`the power of God,`"^
footnote:[1 Corinthians 1:24]
who spiritually and internally administers light and life to the souls of men.
This spiritual and powerful administration is the essence of the gospel.
Both Old and New Testaments bear testimony to the incarnation, death, burial,
resurrection, and ascension of the Lord Jesus Christ,
but the real substance of the apostolic gospel does not consist of history and doctrine,
but of the living and sensible operation of the power of God.

We read, that "`Life and immortality are brought to light by the gospel,`"^
footnote:[2 Timothy 1:10]
but what is this life and immortality that the gospel discovered?
Did not mankind believe in a future state before the incarnation of Christ?
Yes, certainly.
Most Jews and Gentiles already believed and held the truth of it.
What life and immortality then is that which is peculiar to the gospel,
and which it is the particular property of the gospel to unveil?
It consists not wholly in an explanation of the external procedure^
footnote:[By "`procedure,`" he means the full course of Christ`'s birth, life, obedience,
sufferings, death, burial, resurrection, and ascension.]
and doctrines of our Lord,
but chiefly in that spiritual gift He procured for us through His sufferings,
which is the life and power that the immortal Spirit of God
manifests in the believing and obedient soul--that is,
the Spirit who quickens those who have been dead in trespasses and sins,
and alienated from the life of God.

The very core of the gospel is the issuing forth
of this Spirit of life into the hearts of men.
"`Keep your heart with all diligence,`" says the wise man,
"`for out of it are the issues of life.`"^
footnote:[Proverbs 4:23]
Now, these issues of life arise _in_ the heart of man, but not _from_ the heart itself;
for were it so, the heart or soul would be its own quickener and savior.
But Christ alone is "`the Way, the Truth, and the Life,`"^
footnote:[John 14:6]
and therefore the issuings of life work in and through the heart by His Spirit.
The divine influence of this Spirit is the true life of the soul,
that which renders it living;
and void of this it cannot be (in a gospel sense) considered a living soul.
Though all souls endure to eternity, eternal duration is not eternal life.
To exist without this life, is to be spiritually dead.
It is therefore imperative that each soul wait for, feel after,
and find this immortal life, and also learn to keep to it with all diligence,
that it may experience the daily issues thereof for its comfort and preservation,
as "`a fountain of water springing up to everlasting life.`"^
footnote:[John 4:14]
