== Chapter 13. Spiritual Worship and Revelation

It is true that we recommend silence and stillness in our religious assemblies;
and seeing our manner of worship is misunderstood by many,
and often treated with ridicule,
I shall take this opportunity to offer some explanation of it.
We look upon divine worship to be the most solemn act
that man is capable of being engaged in;
and in consideration of the high and inconceivable majesty of Almighty God,
we think it our duty to approach Him with the greatest reverence.
Every thinking person, who is in any degree sensible of the love and fear of God,
must esteem it a serious thing to present himself to the special notice of the infinite,
omnipresent, eternal Being.
Under a sense of this, the wise man advises,
"`Walk prudently when you go to the house of God;`"--or enter upon worship--
"`and draw near to hear rather than to give the sacrifice of fools,
for they do not know that they do evil.
Do not be rash with your mouth, and let not your heart utter anything hastily before God.
For God is in heaven, and you on earth; therefore let your words be few.`"^
footnote:[Ecclesiastes 5:1-2]
This man well knew, as he expresses it, that both
"`the preparations of the heart in man, and the answer of the tongue, is from the Lord;`"^
footnote:[Proverbs 16:1]
and this accords with what our Savior says--"`Without Me you can do nothing.`"^
footnote:[John 15:5]
We, therefore, cannot perform divine worship acceptably but by His assistance.
Indeed, this ability must be received in spirit; for the apostle says,
"`The Spirit also helps in our weaknesses;
for we know not what we should pray for as we ought.`"^
footnote:[Romans 8:26]
This being as certainly our case as it was the
case of the apostles and primitive believers,
it is incumbent upon us to wait for that Spirit which is
requisite to help our weaknesses in order to pray as we ought.
No forms of devotion of men`'s invention can take the place of the Spirit.
The same apostle further says,
"`Through Him we both have access by one Spirit unto the Father.`"^
footnote:[Ephesians 2:18]
Seeing, therefore, that both our help and our access is through the Spirit of Christ,
the renewal of which is at His pleasure and not ours, we must necessarily wait for it.

Now, this waiting must be in stillness of mind from the common course of our own thoughts,
from all wandering imaginations, and also in silence from the expression of words;
for the utterance of words is not waiting, but acting.
Words are necessary to convey the sense of one person to another,
but it is not so with the Omniscient Being who is a universal Spirit,
and everywhere Almighty, who therefore has no need either of the use of bodily organs,
instruments, or the sound of words, to communicate with the spirit of man.
If, in order to worship, the mind does not settle into stillness,
the passions will be at work,
which often agitate it into enthusiastic heats and vague imaginations.
But in true stillness and singleness of soul towards God,
these are silenced and subjected.
The still small voice of the Inspirer of all good then comes to be heard,
and the mind being closely engaged in attention thereunto,
and answering it in faith and humble submission, feels divine life and love spring up.
In this the soul receives ability to truly worship the great
Author of its existence and the heavenly Supplier of its needs,
with a devotion which no outward forms can reach.

This worship is not entered upon by totally laying aside our faculties,
and falling into a senseless stupor, as some superficial observers have imagined,
but by a real turning of the mind and heart,
with an attention fixed singly and inwardly upon the only Object of all adoration,
in patient yet fervent desire after Him.
Thus, according to the Hebrew, the experienced Psalmist advises,
"`Be silent to the Lord, and wait patiently for him.`"^
footnote:[Ps. 37:7--Literal Translation of Hebrew]
And respecting his own practice, he says,
"`Truly my soul is silent upon God,`" adding this compelling reason,
"`from Him comes my salvation.`"^
footnote:[Ps. 62:1--Literal Translation of Hebrew]
In verse 5 of the same Psalm he applies the exhortation to himself:
"`My soul, wait you only upon God, for my expectation is from Him.`"
Great encouragement he had thus to wait, as appears in Psalm 40, where he says,
"`I waited patiently for the Lord, and He inclined unto me, and heard my cry.
He brought me up also out of a horrible pit, out of the miry clay,
and set my feet upon a rock, and established my goings.
And He has put a new song into my mouth, even praise unto our God.`"^
footnote:[Psalms 40:1-3]

Jeremiah bears testimony to the same practical and profitable doctrine:
"`It is good that a man should both hope and quietly wait for the salvation of the Lord.
It is good for a man that he bear the yoke in his youth.
Let him sit alone and keep silent, because God has laid it on him.`"^
footnote:[Lamentations 3:26-28]
Silent waiting was in practice among the prophets and those that attended them,
as appears in the prophecy of Ezekiel.
We find the spirit of the prophet was engaged in divine vision,
while the elders of Judah sat before him,
as it is described beginning in the first verse of the eighth chapter.
During the time of this vision,
it cannot be supposed that he was either speaking to them, or they to him,
or to each other.
This was not a singular instance of their meeting together this way,
for it was the manner of God`'s people to thus congregate with the prophets,
as the following censure indicates: "`They come to you as people do,
they sit before you as My people, and they hear your words, but they do not do them.`"^
footnote:[Ezekiel 33:31]

In this solemn practice,
we have often been thankfully enabled to acknowledge
the truth of that gracious declaration of our Lord,
"`Where two or three are gathered together in my name,
there am I in the midst of them.`"^
footnote:[Matthew 18:20]
Here we have found the fulfilling of that promise,
"`They that wait upon the Lord shall renew their strength,`"^
footnote:[Isaiah 40:31]
and the certainty of that assertion, "`The Lord is good unto them that wait for Him,
to the soul that seeks Him;`"^
footnote:[Lamentations 3:25]
and also the necessity and authority of that wise command,
"`Be still, and know that I am God.`"^
footnote:[Ps. 46:10]

Because this silent waiting appears to us to be indispensable, in the first place,
for the worship of God in Spirit and truth,
it is always our practice to begin meetings this way;
for we believe the Lord ought to have the direction and attention of our hearts.
And if He is pleased to influence anyone (under due preparation) to vocally appear,
either by way of address to Himself in prayer, or to us in preaching,
we never hinder such appearances,
but rather silently assist them according to our measures.
If it prove that none are so concerned to speak, we sit the time through in silence,
wherein true inward worship is often experienced.
However,
we never appoint any meeting with intent that it shall be held throughout in silence,
as some have mistakenly imagined;
for our aim is to be led and guided by the good Spirit of God,
and more especially in the solemn acts of divine worship.
It would be a happy thing if all (among us as well as others) were so led by the Spirit,
but the case appears otherwise with too many; for many sit unconcerned,
in expectation of hearing vocal ministry instead of waiting upon God,
and therefore often meet with disappointment.
The apostle said in his age, "`They are not all Israel, which are of Israel.`"^
footnote:[Romans 9:6]
So we must also acknowledge that all who have descended
from faithful ancestors are not themselves faithful;
but the defect is in themselves, and not in the principle.

It is true, we insist that the Spirit of Truth ought to be our, and every man`'s leader,
and that this Spirit is an infallible guide,
and that so far as anyone faithfully follows it, they are infallibly led, and no further.
Yet we never did, nor do profess, that all in society with us are so led,
or even sufficiently seek to be so.
Nor was this the case among the primitive Christians themselves.
Indeed, we well know, and freely acknowledge, that we have all sinned,
and come short of the glory of God, and that without repentance and regeneration,
we must forever fall short of it.
We are also sensible, that upon due confession, submission,
and sincere obedience to the manifestations of Christ, the Light of men,
"`He is faithful and just to forgive us our sins,
and to cleanse us from all unrighteousness;`"^
footnote:[1 John 1:9]
and if we "`walk in the light, as He is in the light,
we have fellowship one with another,
and the blood of Jesus Christ His Son cleanses us from all sin.`"^
footnote:[1 John 1:7]

But now, honest reader, could anything but either gross ignorance, envy,
or malevolence,
infer from our entire dependence upon the Spirit
that we profess _ourselves_ to be infallible?
Yet, in this way our doctrines have been discolored
by our adversaries from the very beginning,
and our present opposers follow in the same track,
repeatedly upbraiding us by this allegation.
Nevertheless, even as "`life is more than food, and the body more than clothing,`"^
footnote:[Luke 12:23]
we profess that the immediate influence of the Spirit of
Christ is greater than the Scriptures that testify of Him,
as also any man`'s interpretation of them and practices taken from them.
The original, essential, and primary guide, in all Christian life, ministry, and worship,
is that revelation and empowering which comes
immediately from the Spirit of God into a man`'s heart.

That many (who call themselves Christians) are unfamiliar with the openings
and motions of the Holy Spirit is no argument against this doctrine,
for it is the capacity of every created soul to be "`led by the Spirit of God.`"^
footnote:[Romans 8:14]
For "`if we live by the Spirit,`" says the apostle,
we should also "`walk by the Spirit,`"^
footnote:[Galatians 5:25]
learning to "`worship God in the Spirit,`"^
footnote:[Philippians 3:3]
"`pray in the Spirit,`"^
footnote:[Jude 1:20]
"`love in the Spirit,`"^
footnote:[Colossians 1:8]
"`obey through the Spirit,`"^
footnote:[1 Peter 1:22]
etc.

In order to demonstrate this thing further, let me observe,
that the soul of man has not only a faculty of understanding,
by which it ordinarily thinks and unites, divides, compares, or forms ideas,
but also a hidden power of internal sensation,
or of perceiving spiritual objects by an inward and spiritual sense.
Until the beams of divine light shine upon him,
man necessarily remains entirely unacquainted with this sense,
even as an unborn child remains unaware of its faculties of sight and hearing.
For though a child may be completely formed in the womb,
and possess every organ proper to bodily sensation,
yet it is not empowered to exercise them, or even to know it has them,
till it be brought forth into the medium necessary for the use of them,
composed of the light and air of this world.
Then it suddenly discovers the various senses and natural powers which, before its birth,
it could neither have understood or used.
In like manner, the natural man must be delivered out of his natural darkness,
into the luminous and life-giving influence of that divine Word, or Spirit,
which is most emphatically called the true light and life of men.
Thus born of the Spirit into this proper medium of divine knowledge,
the soul is made acquainted with that spiritual sense it could neither discover,
nor believe pertained to it, while still in its natural state.
This is not a new natural faculty added, but an inward power of the soul newly opened,
and brought into its proper place and use.
Words are inadequate to express this internal
sense felt in the soul under divine influence.
It cannot be clearly conveyed to the understanding of the unexperienced;
for it is not an image, but a sensation,
impossible to be conceived other than by its own impression.
So true is that expression of the apostle, "`Eye has not seen, nor ear heard,
neither have entered into the heart of man,
the things which God has prepared for them that love Him;
but God has revealed them unto us by his Spirit.`"^
footnote:[1 Corinthians 2:9-10]

It is upon this consideration that we insist upon divine light being
an inward sensation which cannot be adequately communicated from one
man to another by reasoning or verbal description.
For if a person should give the most clear and lively description
possible of the light of the sun to a man blind from his birth,
it would only communicate an idea or notion of the light, but not the light itself.
This might be called a revelation concerning the light,
but it is not the revelation of the light itself.
This no man can receive except by his own immediate sensation.
Divine revelation is a disclosure of something to the understanding by the Holy Spirit,
which is not in the mind`'s own power to discover.
The Holy Spirit does this in a variety of ways, such as:
by unveiling itself by its own influence (in measure) upon the soul,
and giving it an internal sense of its presence;
or by giving the soul a clear sense of its own state and condition;
or by opening the mind into the knowledge of the
divine will concerning persons or things,
or into a true sense of Scriptures,
or a deeper understanding of doctrines than it
could ever reach without divine illumination, etc.
All of this is truly internal and immediate revelation.
What is now commonly considered the only revelation still existing,
and ever to exist--the Bible--should more correctly be
called the _fruit_ of revelation than the thing itself,
for it is a scriptural record of things revealed.
These writings were most certainly breathed by
the Spirit unto those who directly received them;
but the many and different interpretations of man put upon them,
for many generations past,
demonstrate that these words are not truly a revelation to those who mistake them;
nor can they ever become such to man until he
knows the holy Author to be their Interpreter.
For, "`no prophecy of Scripture is of any private interpretation,
for prophecy never came by the will of man,
but holy men of God spoke as they were moved by the Holy Spirit.`"^
footnote:[2 Peter 1:20-21]

Our Lord showed his disciples that the Spirit of Truth, the Comforter,
should not only bring to their remembrance what He had told them,
show them things to come, and lead them into all truth, but it should likewise,
"`reprove the world of sin, of righteousness, and also, of judgment.`"^
footnote:[John 16:8]
This divine Visitor can appear to the mind of man in words, or without words;
by the sensations of compunction and remorse, in the sharpness of reproof,
or in the healing touches of consolation; whether it manifests itself as light,
or sheds abroad its life and love into the heart;
whether it darts in upon it as lightning, or settles it in a holy serenity;
whether it fills it with faith, or inflames it with zeal; in all these ways,
seeing it proceeds not by a messenger,
but by its own immediate communication to the rational soul of man,
it is properly called internal immediate revelation.
This divine Spirit is the living source of truth and virtue in man,
without which all exterior laws and precepts would avail very little.
And when, through faithfulness thereunto,
the Spirit of God is enlarged and advanced over all else in the soul,
it is found to be a sure foundation, which neither the wisdom of the wise,
the reasoning of the confident, the juggling of the crafty, the derision of the reviler,
the rage of the persecutor, nor even the gates of hell can prevail against.
