== Chapter 14. The Spirit, the Gospel, and the Kingdom

We believe that all men, at times,
have felt the reproving witness of the Spirit of God in their consciences,
which gives them a convicting knowledge of Him;
and if they continue to rebel against this light,
they become progressively darkened towards it.
Job testifies, "`There are those who rebel against the light;
they do not know its ways, nor abide in its paths.`"^
footnote:[Job 24:13]
And Paul likewise says,
"`Not liking to _retain_ God in their knowledge,`"
(showing that they had at least some measure of it)
"`He gave them over to a reprobate mind.`"^
footnote:[Romans 1:28]
Our principle teaches that
"`the grace of God that brings salvation has appeared to all men,`"^
footnote:[Titus 2:11]
first as a convictor, or convincer of sin.
Thus the Lord stands at the door of man`'s heart and knocks for entrance,
and if the heart opens to Him, and abides in the ability that He furnishes,
sincerely desiring and seeking to obey His motions, the Lord will, by due degrees,
increase the operation of grace therein,
till it prove itself the power of God unto salvation.
Then, and not till then,
does the mind become sensible of the saving knowledge of this divine Spirit.
Yet, even before this,
while the soul knew nothing more of it than merely its convictions,
man could not be said to be totally ignorant of an internal,
immediate sense of that grace which is saving, both in its nature and intention,
though it was not endued with the true saving knowledge of it.

We have all along uniformly acknowledged,
as fully as any professors of Christianity can do,
that the gospel came in word as well as in power; but not in word only,
but also in power, even in the power of the Holy Spirit.
And we are sensible that this divine power, from which the words sprang,
is the very essence of the gospel, and the words are but the outward expression,
or exterior declaration, by which the power is preached and recommended.
To this essential, internal grace, power, and Spirit of God,
the apostles called and pressed their hearers,
as well as to the belief in the outward coming and process^
footnote:[Phipps uses the word "`process`" in the same sense he used "`procedure`"
previously--meaning the full course of Christ`'s birth,
life, obedience, sufferings, death, burial, resurrection, and ascension.]
of the Messiah then past.
They taught them, that "`Christ was once offered to bear the sins of many,
and unto them that look for Him, He shall appear the second time,
without sin unto salvation.`"^
footnote:[Hebrews 9:28]
This second appearance of Christ,
we do not understand to mean His coming for
judgment at the great day of general decision;
for then He will come to determine the final state of both the
righteous and unrighteous--not to salvation only,
but to condemnation also.
But this second appearance is unto the salvation of those who look for Him to that end.
Accordingly, the apostle thus prays for the believers,
"`May the Lord direct your hearts into the love of God,
and into the patient waiting for Christ;`"^
footnote:[2 Thessalonians 3:5 KJV]
and he describes the Corinthians as "`waiting for the coming,`" or renewed appearance,
"`of our Lord Jesus Christ.`"^
footnote:[1 Corinthians 1:7]

Though our Savior empowers and employs His messengers to publicly declare His will,
and to call people to the work of repentance and regeneration,
He does not deputize them to do the work for Him.
It is not the words that His messengers deliver, nor any human application of them,
which can perform this great business of salvation.
"`Lord,`" says the prophet,
"`You will ordain peace for us; for You also have wrought all our works in us.`"^
footnote:[Isaiah 26:12]
The Spirit of the high and holy One is the true
source and cause of all real good that is done,
all real virtue that is wrought, either in the church in general, or any of its members.
It is the Spirit that gives understanding,
and unveils the knowledge of the things of God;^
footnote:["`I said, days should speak, and multitude of years should teach wisdom.
But there is a spirit in man,
and the inspiration of the Almighty gives them understanding.`"
Job 32: 7-8 -- "`Eye has not seen, nor ear heard,
neither have entered into the heart of man,
the things which God has prepared for them that love Him.
But God has revealed them to us through His Spirit.
For the Spirit searches all things, yes, the deep things of God.
For what man knows the things of a man except the spirit of the man which is in him?
Even so no one knows the things of God except the Spirit of God.`" 1 Cor. 2:9-11]
quickens and makes alive,^
footnote:["`It is the Spirit that quickens, the flesh profits nothing.`"
John 6:63 -- "`The letter kills, but the Spirit gives life.`"
2 Cor. 3:6 -- "`But if the Spirit of Him who
raised Jesus from the dead dwells in you,
He who raised Christ from the dead will also give life to your
mortal bodies through His Spirit who dwells in you.`" Rom. 8:11]
mortifies,^
footnote:["`For if you live according to the flesh you will die;
but if by the Spirit you put to death the deeds of the body, you will live.`" Rom. 8:13]
circumcises,^
footnote:["`Circumcision is that of the heart in the Spirit,
and not in the letter.`" Rom. 2:29]
baptizes,^
footnote:["`By one Spirit we are all baptized into one body.`" 1 Cor. 12:13]
sanctifies,^
footnote:["`But you are washed, but you are sanctified,
but you are justified in the name of the Lord Jesus, and by the Spirit of our God.`"
1 Cor. 6:11]
regenerates,^
footnote:["`Except a man be born of water and the Spirit,
he cannot enter into the kingdom of God.
That which is born of the flesh, is flesh; and that which is born of the Spirit,
is Spirit.`" John 3:5-6]
sets free,^
footnote:["`The law of the Spirit of life in Christ
Jesus has made me free from the law of sin and death.`" Rom. 8:2]
strengthens, and enables to obey.^
footnote:["`That He would grant you, according to the riches of His glory,
to be strengthened with might, by His Spirit, in the inner man.`" Eph. 3:16]
In the Spirit is the true light,^
footnote:["`In Him was life, and the life was the light of men.
-- That was the true light which enlightens every man that comes into the world.`"
John 1:4,9 -- "`God, who commanded the light to shine out of darkness,
has shined in our hearts, to give the light of the knowledge of the glory of God,
in the face of Jesus Christ.`" 2 Cor. 4:6]
the life,^
footnote:["`The Spirit gives life.`" 2 Cor. 3:6]
the love,^
footnote:["`Who also declared unto us your love in the Spirit.`" Col. 1:8]
the waiting,^
footnote:["`We, through the Spirit, wait for the hope of righteousness, by faith.`"
Gal. 5:5]
the walking,^
footnote:["`If we live in the Spirit, let us also walk in the Spirit.`" Gal. 5:25]
the fellowship,^
footnote:["`If any fellowship of the Spirit.`" Phil. 2:1]
and communion of the gospel.^
footnote:["`Have been all made to drink into one Spirit.`" 1 Cor. 12:13]
In the Spirit is true prayer made,^
footnote:["`The Spirit also helps our weaknesses,
for we know not what we should pray for as we ought,
but the Spirit makes intercession for us, etc.`" Rom. 8:26]
access to the throne of grace opened,^
footnote:["`Praying always with all prayer and supplication in the Spirit,
and watching thereunto with all perseverance.`"
Eph. 6:18 -- "`Praying in the Holy Spirit.`" Jude 20]
and acceptable worship performed.^
footnote:["`Through him we both have an access by one Spirit unto the Father.`" Eph. 2:18]
The Spirit is the covering of God`'s people,^
footnote:["`Woe to the rebellious children, that cover with a covering,
but not of My Spirit.`" Isa. 30:1]
their guide,^
footnote:["`When He the Spirit of Truth is come, He will guide you into all Truth.`"
John 16:13]
their leader,^
footnote:["`If you are led by the Spirit you are not under the law.`"
Gal. 5:18 -- "`As many as are led by the Spirit of God, these are the sons of God.`"
Rom. 8:14]
their comforter,^
footnote:["`I will pray the Father, and He shall give you another Comforter,
that He may abide with you forever, even the Spirit of Truth.`" John 14:16-17]
their seal,^
footnote:["`God, who has also sealed us,
and given the earnest of the Spirit in our hearts.`"
2 Cor. 1:22 "`In whom, after you believed,
you were sealed with the Holy Spirit of promise.`"
Eph.1:13 -- "`Grieve not the Holy Spirit of God, whereby you are sealed,
unto the day of redemption.`" Eph. 4:30]
the inward earnest of an everlasting inheritance to them.
In sum,
the Spirit of God is the all-effective power and virtue of the gospel ministration,
to which all the Scriptures here cited undeniably bear witness.
In all these respects, the Holy Spirit operated mightily among the primitive believers,
and we maintain that the same spiritual operations are
necessary in this and every generation.

With regard to the gospel, we acknowledge that the word gospel, in an extended sense,
may include both the history and the mystery,
the outward and the inward process of our Savior; for the gospel comes not in word only,
but also in power and in the Holy Spirit.^
footnote:[1 Thessalonians 1:5]
We believe this power of the Holy Ghost to be the internal, essential part,
and the words the exterior declaration and expression of it.
We admit the history deserves a share in the title,
but it must not detract from the power, which is the life and reality of it,
lest people be deceived into a belief that the
gospel essentially consists of nothing but words.

We heartily acknowledge that the apostle`'s preached the gospel when, by inspiration,
they declared the historical process of Christ;
but we cannot concede that this comprehended the whole of their gospel.
For we read in their writings that the gospel is the power of God unto salvation,
and that it shines as a light in the heart to give the knowledge of the glory of God.
The doctrines of the gospel are also called the gospel,
and the preaching of them is termed preaching the gospel;
but it is evident that neither the history nor the
doctrines are the essence or substance of the thing.
For in Galatians, after the apostle had said,
"`If any man preach any other gospel unto you than that you have received,
let him be accursed;`"^
footnote:[Galatians 1:9]
he then shows what he meant by the gospel they had received, "`But I make known to you,
brethren, that the gospel which was preached by me is not according to man.
For I neither received it from man, nor was I taught it,
but it came through the revelation of Jesus Christ... But when it pleased God,
who separated me from my mother`'s womb and called me through His grace,
to reveal His Son in me, that I might preach Him among the Gentiles,
I did not immediately confer with flesh and blood.`"^
footnote:[Galatians 1:11-16]
The gospel here intended is plainly the immediate
revelation of the Son of God within him,
and not the historical or doctrinal relation of things without him.
Indeed, it is against the opposers of this internal,
essential gospel--which is not of man, nor by man,
but by the revelation of Jesus Christ within man--that
the apostle twice pronounces anathema.

Paul preached the gospel "`not with persuasive words of human wisdom,
but in demonstration of the Spirit and of power`"^
footnote:[1 Corinthians 2:4]
that the faith of his hearers might be fixed in this power of God,
and not in the private interpretations of men`'s wisdom.
His fellow-laborers preached under the influence of the same divine power,
which pricked their hearers in their heart;
and so must all who ever truly preach the gospel.
In coming to the Corinthians,
the apostle declared he would "`know not the words of them that are puffed up,
but the power.
For the kingdom of God is not in word, but in power.`"^
footnote:[1 Corinthians 4:19-20]
This everlasting power is the Spirit of the gospel,
wherein it mainly and most essentially consists;
and so Paul directs his readers to turn away from such who
"`have a form of godliness, but deny its power.`"^
footnote:[2 Timothy 3:5]
To confine the whole of the gospel to mere historical tidings,
or to reduce it into a bare report,
is to exclude the powerful reality which gives deliverance,
as though the report were the Savior, and the notion the salvation.
This we cannot admit; for we know no Savior but Christ,
nor any salvation without His power.

Tertullian wrote to the same purpose fifteen hundred years ago.
In his Apology, chapter 17 he says, "`Surely the soul was before the letter,
and the Word was before the book... And if you are disposed to understand,
it is not the words of the book, but Christ himself, who is sent into the world,
and who is the gospel.`"
We likewise read in 2nd Corinthians, "`But even if our gospel is veiled,
it is veiled to those +++[+++Literally '`veiled in those`' Gr. _'`en tois`'_]
who are perishing, whose minds the god of this age has blinded, who do not believe,
lest the light of the gospel of the glory of Christ, who is the image of God,
should shine on them.
For we do not preach ourselves, but Christ Jesus the Lord,
and ourselves your bondservants for Jesus`' sake.
For it is the God who commanded light to shine out of darkness,
who has shone in our hearts to give the light of the knowledge
of the glory of God in the face of Jesus Christ.`"^
footnote:[2 Corinthians 4:3-6]
Here the apostle teaches that the gospel they preached was Christ, showing His face,
or manifesting Himself as the image of God in their hearts;
and that this gospel was only hid, or obscured, in the minds of those,
who through unbelief therein, or unfaithfulness thereto, had become blinded towards it,
by him who is called the god of this world,
because he is obeyed by those who walk according to the course of this world.

John the Evangelist asserts that Christ, the Logos or Word of God,
is the only true light and life of men,
and the source of all real knowledge of God that has ever been
revealed to any people for the life and happiness of their souls.
This accords with the prophecies of the gospel covenant:
"`I will put my law in their inward parts,
and write it in their hearts,`" and "`For they shall all know me,
from the least of them to the greatest of them.`"^
footnote:[Jeremiah 31:33-34]
This could not intend the knowledge of Christ incarnate,
for that appearance was external, in one nation only, and of short duration.
Nor could it mean the knowledge of the Scriptures;
for a man may know them from beginning to end, believe them to be true,
form his practice according to his apprehensions of the sense of them,
and yet not know the Lord.
The Jews had the law, the prophets, and the Scriptures which existed in their time;
yet the Almighty, by the mouth of the same prophet, declares, "`My people are foolish,
they have not known me.`"^
footnote:[Jeremiah 4:22]
Nor was it possible they should know Him without divine assistance; therefore he says,
"`I will give them a heart to know me.`"^
footnote:[Jeremiah 24:7]
And in Ezekiel, "`A new heart also will I give you,
and a new Spirit will I put within you&hellip; I will put my Spirit within you.`"^
footnote:[Ezekiel 36:26-27]

Thus, the gospel of God is to be received and known by the
internal writing of the divine Word in the heart,
which puts the law of light and life within man.
Indeed, this is "`the gospel of the kingdom of God`"^
footnote:[Mark 1:14]
which kingdom begins as a mustard seed, a pearl, a pinch of leaven,
or a small stone "`cut out of the mountain without
hands,`" but which becomes a great mountain,
breaks in pieces and consumes all other kingdoms, and fills the earthly heart of man.
This kingdom, Jesus said, "`does not come with observation; nor will they say,
'`See here!`' or '`See there!`' For indeed, the kingdom of God is within you.`"^
footnote:[Luke 17:21]
Some, to suit their purpose, choose to read these last words,
"`the kingdom of God is _among_ you.`"
But this reading destroys the contrast that was evidently intended by our Savior,
who was here answering a question put to Him by the Pharisees
concerning their expectation of an outward kingdom.
The Lord informs them that the kingdom of God is an inward kingdom,
and here shows the difference between an outward and visible form
(which men are capable to point out by their '`lo here,`' and '`lo there`')
and His own internal, spiritual dominion.
Furthermore, the word in the original Greek is _entos,_
which properly signifies _within_ or _inside,_
and not _en_ which can be rendered _in_ or _among._

If any ask, '`What is the kingdom of heaven, or of God?`' I answer:
Though He is indeed the Almighty Sovereign of the entire universe,
yet His kingdom is more particularly that wherein He so completely
governs as to be always cheerfully and perfectly obeyed;
where He is the sole mover of all that is done;
where He is glorified in all that is done,
and where He communicates His own glory and felicity without mixture.
This kingdom can neither be entered, nor even seen into by man,
except through the new birth of the Holy Spirit,
whereby the soul experiences a being born into it--a being delivered from
the power of darkness and translated into the kingdom of the dear Son of God.
By this alone the spirit of man enters the kingdom, and through faithfulness,
is enabled to make advances therein while still in the body.
This kingdom stands not in place,
nor in any '`here or there,`' and it is therefore vain
to direct men to it by "`lo here,`" or "`lo there.`"
Rather, it stands in an infinite and heavenly Spirit, life, and nature,
wherein nothing impure can live or enter.
It is the internal dominion, or ruling power of the Holy Spirit in men and angels.
It is that pure influence flowing from the glory of the Almighty, which,
entering into holy souls, makes them friends of God.
In short, the kingdom of God is the dominion of the light and life of the Spirit of God.
Whoever lives under the sensible influence and government of this, lives in the kingdom.
This is the kingdom of the saints militant on earth,
and of the saints triumphant in heaven,
which is only experienced by the sanctified in Christ Jesus--in part while in this world,
and in fulness in the world to come.
